#!/usr/bin/env node
// Approve directionally + close HubSpot replacement spec BC todo
// 9859064184 per Ali's "1" greenlight. Sign-off based on stack
// summary + 4-phase rollout. Detailed per-row review skipped since
// the actual gating items are Sohail's 6 answers + Lead API spec.

const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../../../.env') });

const BC = process.env.BASECAMP_ACCESS_TOKEN || '';
const H = { Authorization: 'Bearer ' + BC, 'User-Agent': 'Colaberry', Accept: 'application/json', 'Content-Type': 'application/json' };
const BASE = 'https://3.basecampapi.com/3945211/buckets/7482752';
const TODO = 9859064184;

const APPROVAL = `<div>
<p><strong>Approved directionally. Closing this todo. Execution gating sits on Sohail's 6 answers + the enterprise.colaberry.ai Lead API spec, not on per-row spec sign-off.</strong></p>

<h3 style="margin:18px 0 6px;font-size:14px">What is approved (Ali sign-off 2026-06-03)</h3>
<ul style="font-size:12.5px;margin:0 0 8px;line-height:1.6">
<li><strong>Recommended stack</strong> — Resend (email, ~$20/mo replacing HubSpot Marketing Hub Pro ~$890/mo), PostHog (analytics with Lead + Contact joins), Cal.com (meetings, advisor-per-page), Metabase OR custom Next.js dashboards in enterprise.colaberry.ai, instantly.ai (cold outreach). $12K-$15K/yr saved vs HubSpot Marketing Hub.</li>
<li><strong>4-phase rollout order</strong> — 3a Foundation (2 wk: Lead API + Contact import + dual-write swap + UTM capture) -> 3b Communications (2 wk: Resend + Open House nurture A/B + class reminders + cold outreach pick) -> 3c Analytics (2 wk: PostHog + funnel dashboard + custom dashboards) -> 3d Wind-down (Cal.com + Send button + HubSpot termination). Dependency order is correct: Lead API + Contact import has to land before Comms can fire.</li>
<li><strong>Build vs integrate vs skip per-row recommendations</strong> — sign-off on the framework. Tejesh's call on each of the 11 rows stands; if a specific row needs a re-look during execution, raise it on the relevant phase todo.</li>
</ul>

<h3 style="margin:18px 0 6px;font-size:14px">What still gates execution (Tejesh's stated dependencies, not changed by this approval)</h3>
<ul style="font-size:12.5px;margin:0 0 8px;line-height:1.6">
<li>Sohail's 6 answers (referenced in the 2026-05-19 status comment)</li>
<li>enterprise.colaberry.ai Lead API spec</li>
</ul>
<p style="font-size:12.5px;margin:0">Both of those should be tracked as their own focused execution todos with due dates. They are not new asks generated by this approval - they were Tejesh's own call-outs from the May 19 status comment.</p>

<h3 style="margin:18px 0 6px;font-size:14px">Non-goals of this approval</h3>
<ul style="font-size:12.5px;margin:0 0 8px;line-height:1.6">
<li>Per-row done-criteria audit on the 11 capability rows. Each row's done-criteria will be enforced via that row's execution todo when 3a/3b/3c/3d work starts.</li>
<li>Vendor procurement (Resend, PostHog, Cal.com, instantly.ai contracts + billing setup). Sign-off here is on the architectural choice, not on signing the contracts.</li>
<li>HubSpot termination date. That belongs in phase 3d once the replacements are proven in production.</li>
</ul>

<p style="font-size:12.5px;color:#475569;margin-top:14px;font-style:italic">Closing this todo. Session: CC-20260603-v7da.</p>
</div>`;

(async () => {
  console.log('1. Posting approval comment...');
  const r = await fetch(`${BASE}/recordings/${TODO}/comments.json`, {
    method: 'POST', headers: H, body: JSON.stringify({ content: APPROVAL }),
  });
  if (!r.ok) throw new Error(`POST -> ${r.status} ${await r.text()}`);
  const c = await r.json();
  console.log('   approval:', c.id, c.app_url);

  console.log('\n2. Marking todo complete...');
  const m = await fetch(`${BASE}/todos/${TODO}/completion.json`, { method: 'POST', headers: H });
  console.log('   status:', m.status);

  console.log('\n=== DONE ===');
  console.log('Approval comment:', c.app_url);
  console.log('Todo', TODO, 'marked complete');
})().catch(e => { console.error('FAIL:', e.stack || e.message); process.exit(1); });
