#!/usr/bin/env node
/**
 * Generate the tenant-isolation evidence document (DEC-05).
 *
 * CPN's data isolation is a formal grant and donor requirement. Satisfying it needs two
 * things: the control, and evidence the control works. This produces the second.
 *
 * THE DESIGN CONSTRAINT THAT MATTERS: the document is generated by RUNNING the isolation
 * tests and reading their real results. It is never hand-written. A hand-written
 * assurance document drifts the moment someone changes a guard, and then it is worse
 * than nothing, because it is a confident claim that happens to be false. If a test is
 * deleted, its line disappears from the evidence. If a test fails, the document says so
 * and the script exits non-zero.
 *
 * Run:  node backend/src/scripts/generateIsolationEvidence.js
 *       node backend/src/scripts/generateIsolationEvidence.js --out <path>
 */
const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const BACKEND = path.resolve(__dirname, '..', '..');
const REPO = path.resolve(BACKEND, '..');

/**
 * The suites that constitute the isolation control. Each entry says what the suite is
 * evidence OF, in language an auditor can read without knowing the codebase.
 */
const EVIDENCE_SUITES = [
  {
    pattern: 'modules/tenancy/__tests__/tenantAuthorization.test.ts',
    control: 'Access control',
    claim:
      'An operator can reach only the tenants they hold an active membership in. Roles do not ' +
      'carry from one tenant into another. Unclassified records are reachable only by a platform ' +
      'administrator. A request with no identity matches no records at all.',
  },
  {
    pattern: 'modules/tenancy/__tests__/tenantAccessGuards.test.ts',
    control: 'Audit trail',
    claim:
      'Every boundary decision is recorded, refusals included, before any error is raised. ' +
      'Cross-tenant administrator access is recorded on the permitted path as well. The audit ' +
      'never changes an access outcome: if the audit store is unreachable the boundary still ' +
      'holds and the lost record is reported.',
  },
  {
    pattern: 'modules/tenancy/__tests__/leadContextService.test.ts',
    control: 'Contact confidentiality',
    claim:
      'One person may hold relationships with several brands without those relationships being ' +
      'visible to each other. Consent is recorded per brand and is never inherited across ' +
      'brands or silently withdrawn.',
  },
  {
    pattern: 'modules/communications/__tests__/senderProfileService.test.ts',
    control: 'Outbound identity',
    claim:
      'A campaign cannot send using another brand’s sending identity; the attempt is refused ' +
      'before any message reaches the provider. Live sending is refused until the sending ' +
      'domain is verified and the required legal footer details are present.',
  },
  {
    pattern: 'modules/attribution/__tests__/journeyLinkService.test.ts',
    control: 'Cross-site identification',
    claim:
      'Context passed between sites carries identifiers only and never an email address. Links ' +
      'expire, and altered or expired links are refused.',
  },
];

function runSuite(pattern) {
  const args = [
    'jest',
    '--silent',
    '--json',
    '--testPathPattern',
    pattern.replace(/\//g, '[\\\\/]'),
  ];
  try {
    const out = execFileSync('npx', args, {
      cwd: BACKEND,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
      stdio: ['ignore', 'pipe', 'pipe'],
      shell: process.platform === 'win32',
    });
    return JSON.parse(out.slice(out.indexOf('{')));
  } catch (err) {
    // jest exits non-zero on failure but still prints the JSON report, which is exactly
    // what a failing evidence run needs to show.
    const stdout = err.stdout ? String(err.stdout) : '';
    const brace = stdout.indexOf('{');
    if (brace >= 0) {
      try {
        return JSON.parse(stdout.slice(brace));
      } catch {
        /* fall through */
      }
    }
    return { __unreadable: true, message: err.message };
  }
}

function collectAssertions(report) {
  const rows = [];
  for (const suite of report.testResults || []) {
    for (const t of suite.assertionResults || []) {
      rows.push({
        name: [...(t.ancestorTitles || []), t.title].join(' › '),
        status: t.status,
      });
    }
  }
  return rows;
}

function main() {
  const outArgIndex = process.argv.indexOf('--out');
  const outPath =
    outArgIndex > -1 && process.argv[outArgIndex + 1]
      ? path.resolve(process.argv[outArgIndex + 1])
      : path.join(REPO, 'docs', 'architecture', 'multi-tenancy', 'ISOLATION_EVIDENCE.md');

  let commit = 'unknown';
  try {
    commit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: REPO, encoding: 'utf8' }).trim();
  } catch {
    /* not fatal: the document says "unknown" rather than lying */
  }
  const generatedAt = new Date().toISOString();

  const sections = [];
  let totalPassed = 0;
  let totalFailed = 0;
  let unreadable = 0;

  for (const suite of EVIDENCE_SUITES) {
    process.stdout.write(`running ${suite.control} ... `);
    const report = runSuite(suite.pattern);

    if (report.__unreadable) {
      unreadable += 1;
      sections.push({ ...suite, unreadable: true, message: report.message, rows: [] });
      console.log('COULD NOT RUN');
      continue;
    }

    const rows = collectAssertions(report);
    const passed = rows.filter((r) => r.status === 'passed').length;
    const failed = rows.filter((r) => r.status === 'failed').length;
    totalPassed += passed;
    totalFailed += failed;
    sections.push({ ...suite, rows, passed, failed });
    console.log(`${passed} passed, ${failed} failed`);
  }

  const clean = totalFailed === 0 && unreadable === 0;

  const lines = [];
  lines.push('# Tenant Isolation: Evidence of Control');
  lines.push('');
  lines.push('**GENERATED FILE. Do not edit by hand.**');
  lines.push('');
  lines.push(
    'Produced by `backend/src/scripts/generateIsolationEvidence.js`, which runs the isolation ' +
      'tests and reports their real results. Every line below reflects a test that actually ran ' +
      'at the commit named here. If a test is removed its line disappears; if a test fails the ' +
      'document says so. It cannot drift from the behaviour it certifies, because it is not ' +
      'written independently of it.',
  );
  lines.push('');
  lines.push(`- **Commit:** \`${commit}\``);
  lines.push(`- **Generated:** ${generatedAt}`);
  lines.push(`- **Checks passed:** ${totalPassed}`);
  lines.push(`- **Checks failed:** ${totalFailed}`);
  lines.push('');
  lines.push(
    clean
      ? '**Result: every isolation check passed at this commit.**'
      : '**Result: ONE OR MORE ISOLATION CHECKS DID NOT PASS. This document is not an attestation of a working control.**',
  );
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Why this exists');
  lines.push('');
  lines.push(
    'Career Pathways Network is a separate legal entity, and its data isolation is a formal ' +
      'grant and donor commitment rather than an internal preference. A control that silently ' +
      'works produces no evidence that it worked. **The refusals are the evidence**: a record ' +
      'containing only successful reads would demonstrate nothing about a boundary.',
  );
  lines.push('');
  lines.push('## Controls and what each one asserts');
  lines.push('');

  for (const s of sections) {
    lines.push(`### ${s.control}`);
    lines.push('');
    lines.push(s.claim);
    lines.push('');
    if (s.unreadable) {
      lines.push(`> **This suite could not be run.** ${s.message}`);
      lines.push('');
      continue;
    }
    lines.push(`_${s.passed} checks passed, ${s.failed} failed._`);
    lines.push('');
    for (const row of s.rows) {
      const mark = row.status === 'passed' ? 'PASS' : row.status === 'failed' ? 'FAIL' : 'SKIP';
      lines.push(`- \`${mark}\` ${row.name}`);
    }
    lines.push('');
  }

  lines.push('## Scope and limits, stated plainly');
  lines.push('');
  lines.push(
    '- These are automated checks of the enforcement logic. They are not a penetration test ' +
      'and they are not an independent audit.',
  );
  lines.push(
    '- They cover the tenancy layer. They do not cover physical security, database ' +
      'administrator access, backup handling, or any control outside this application.',
  );
  lines.push(
    '- The audit trail records decisions made through the audited guards. A code path that ' +
      'bypasses those guards would not appear here, which is why the guards are the single ' +
      'place a boundary decision is made.',
  );
  lines.push(
    '- Whether any scholarship applicants are minors remains unanswered, and it carries ' +
      'retention and consent obligations that are separate from tenant isolation.',
  );
  lines.push('');

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
  console.log(`\nwrote ${path.relative(REPO, outPath)}`);
  console.log(clean ? 'ALL ISOLATION CHECKS PASSED' : 'ISOLATION CHECKS DID NOT ALL PASS');

  // Non-zero on failure so this can gate a release rather than quietly producing a
  // document that says the control is broken.
  process.exit(clean ? 0 : 1);
}

main();
