#!/usr/bin/env node
// Lay down a minimal project skeleton in each gov-bid build folder.
// Each project is self-contained so it can later be split into its own
// git repo with `git subtree split`. The skeleton mirrors a typical
// Colaberry-style Node + React project: backend Express, frontend
// React, Docker for local dev, fake-data seeds.

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '../../..');
const BUILDS_DIR = path.join(REPO, 'gov-bid-builds');

const PROJECTS = [
  {
    slug: 'tdhca-multifamily',
    intern: 'Akiwam',
    title: 'TDHCA Multifamily Management System',
    agency: 'Texas Department of Housing and Community Affairs',
    closeDate: '2026-06-29',
    bcListId: 9967405074,
    rfpUuid: '2f5fd926-05f6-4d02-9388-c0ae3b141aed',
    elevator: 'Web app for LIHTC application intake, underwriting, asset management, compliance monitoring, and LURA / IRS-8823 / 8609 generation.',
    demoDomain: 'tdhca-demo.colaberry.dev',
  },
  {
    slug: 'tdcj-oig-records',
    intern: 'OBI',
    title: 'TDCJ-OIG Records Management System',
    agency: 'Texas Department of Criminal Justice - Office of Inspector General',
    closeDate: '2026-11-01',
    bcListId: 9967406450,
    rfpUuid: 'cf2f3de4-cb2b-4eb0-85d5-7494cc6693d0',
    elevator: 'Cloud-based law-enforcement RMS with case management, evidence chain-of-custody, multi-jurisdictional search, and CJIS-grade audit log.',
    demoDomain: 'tdcj-rms-demo.colaberry.dev',
  },
  {
    slug: 'utd-residential-life',
    intern: 'Omolola',
    title: 'UTD Residential Life Software for Housing',
    agency: 'University of Texas at Dallas',
    closeDate: '2026-06-30',
    bcListId: 9967407307,
    rfpUuid: '4dc18cd6-a1a3-4bdd-86f4-b4e97c6d6dd7',
    elevator: 'Residential life platform: forms, scheduling, program proposals, mass communications, student profiles, StarRez + Salesforce integration.',
    demoDomain: 'utd-reslife-demo.colaberry.dev',
  },
  {
    slug: 'harris-agenda-meeting',
    intern: 'samrawit',
    title: 'Harris County Agenda + Meeting Management System',
    agency: 'Harris County',
    closeDate: '2026-06-22',
    bcListId: 9967409301,
    rfpUuid: '2e287828-9040-4948-98fe-a0250a5d66a5',
    elevator: 'Agenda construction, live voting, minutes generation, action item tracking, public portal aligned to Harris County USRA.',
    demoDomain: 'harris-meetings-demo.colaberry.dev',
  },
];

function readme(p) {
  return `# ${p.title}

> Working demo / pilot accompanying the Colaberry response to **${p.agency}** RFP. ${p.elevator}

| Field | Value |
|---|---|
| Owner | ${p.intern} |
| RFP close date | **${p.closeDate}** |
| Demo URL (target) | https://${p.demoDomain} |
| BC list (proposal) | https://app.basecamp.com/3945211/buckets/47346103/todolists/${p.bcListId} |
| BC list (build) | created by scaffold script — see Gov Contracts BC project |
| Opportunity Pulse | http://95.216.199.47/admin/bonfire/${p.rfpUuid}/submission-readiness |

## What this is

A web app pilot we ship alongside the proposal. The pilot is a working demonstration of the system the agency is asking for — they can click a link in our proposal and see real screens with seeded fake data flowing through them.

The proposal narrative references this demo URL repeatedly. The demo is the bid's differentiator.

## Two-week sprint goal

Build a working pilot that supports the agency's demo storyline (described in [requirements.md](./requirements.md)) and deploys to a public URL we can paste into the proposal.

## Quickstart

\`\`\`bash
cp .env.example .env
# fill in the env vars
npm install
npm run dev
\`\`\`

See [SETUP.md](./SETUP.md) for the full local development setup.

## Architecture

The full requirements + architectural blueprint generated by the AI Project Architect lives in [requirements.md](./requirements.md). Read it end-to-end before you start coding.

## Demo storyline

The agency demo flow is in the build BC list. Each task is one screen / one feature in the flow. Build top-down.

## Fake-data seeds

\`\`\`bash
npm run seed
\`\`\`

The seed script populates the demo with realistic sample data so visitors see a working system, not empty tables. Seed templates live in [seeds/](./seeds/).

## Deployment

\`\`\`bash
npm run deploy
\`\`\`

Default target: Hetzner VPS at \`95.216.199.47\` with nginx reverse proxy. See [deploy/](./deploy/) for the Dockerfile + compose config.

## Later: split into its own repo

This project currently lives inside the Colaberry Enterprise AI Accelerator repo. To split it into its own repo later:

\`\`\`bash
git subtree split --prefix=gov-bid-builds/${p.slug} -b ${p.slug}-split
git remote add ${p.slug} <new-repo-url>
git push ${p.slug} ${p.slug}-split:main
\`\`\`

See [MOVE_TO_OWN_REPO.md](./MOVE_TO_OWN_REPO.md) for the full migration checklist.
`;
}

function setup() {
  return `# Local Development Setup

## Prerequisites

- Node.js 20+
- Docker (for Postgres + storage)
- A Colaberry GitHub access (the cloned repo is private)

## First-time setup

\`\`\`bash
# 1. Install deps
npm install

# 2. Boot the local stack (Postgres + S3-compatible MinIO)
docker compose up -d

# 3. Copy and fill the env file
cp .env.example .env

# 4. Run migrations
npm run db:migrate

# 5. Seed fake data
npm run seed

# 6. Boot the dev server
npm run dev
\`\`\`

The app should be live at http://localhost:3000.

## Env vars

See \`.env.example\` for the full list. Critical ones:

- \`DATABASE_URL\` — Postgres connection string (default points at the local docker-compose Postgres)
- \`S3_*\` — object storage (default points at local MinIO)
- \`AUTH_SECRET\` — random string, any 32+ char value works locally

## Common scripts

| Command | What it does |
|---|---|
| \`npm run dev\` | Boot the dev server with hot reload |
| \`npm run build\` | Build for production |
| \`npm run seed\` | Wipe + reseed fake data |
| \`npm run db:migrate\` | Apply pending migrations |
| \`npm run db:rollback\` | Roll back the last migration |
| \`npm run lint\` | Run linting |
| \`npm run test\` | Run unit tests |

## If something breaks

Open a Slack thread in \`#gov-contracts\`. Tag \`@CB System\` and describe what you tried.
`;
}

function envExample(p) {
  return `# ---------- App ----------
NODE_ENV=development
PORT=3000
PUBLIC_URL=https://${p.demoDomain}

# ---------- Database ----------
DATABASE_URL=postgres://${p.slug}:dev@localhost:5432/${p.slug.replace(/-/g, '_')}

# ---------- Object storage ----------
S3_ENDPOINT=http://localhost:9000
S3_REGION=us-east-1
S3_BUCKET=${p.slug}-dev
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=minioadmin

# ---------- Auth ----------
AUTH_SECRET=replace_with_32_char_random_string
AUTH_PROVIDER=mock

# ---------- Email (mock for demo) ----------
EMAIL_PROVIDER=mock
EMAIL_FROM="${p.title} <demo@${p.demoDomain}>"

# ---------- Demo seeding ----------
SEED_RESET=true
SEED_USER_COUNT=20
`;
}

function packageJson(p) {
  const name = p.slug;
  return JSON.stringify({
    name,
    version: '0.1.0',
    private: true,
    description: p.elevator,
    scripts: {
      dev: "echo 'TODO: boot dev server' && exit 0",
      build: "echo 'TODO: build' && exit 0",
      seed: "node seeds/index.js",
      'db:migrate': "echo 'TODO: db migrate' && exit 0",
      'db:rollback': "echo 'TODO: db rollback' && exit 0",
      lint: "echo 'TODO: lint' && exit 0",
      test: "echo 'TODO: tests' && exit 0",
      deploy: 'echo "TODO: deploy" && exit 0',
    },
    dependencies: {},
    devDependencies: {},
  }, null, 2);
}

function gitignore() {
  return `node_modules/
.env
.env.local
*.log
dist/
build/
coverage/
.DS_Store
.idea/
.vscode/
tmp/
`;
}

function seedIndex(p) {
  return `// Seed entry point. Populates the demo with realistic fake data so
// visitors see a working system, not empty tables.
//
// Run: npm run seed
//
// SEED_RESET=true wipes existing data first. Default in .env.example.

console.log('[${p.slug}] seeding fake data (TODO: implement)');
console.log('Reset:', process.env.SEED_RESET === 'true');
process.exit(0);
`;
}

function moveToOwnRepo(p) {
  return `# Migrating ${p.title} to its own git repo

This project currently lives inside the Colaberry Enterprise AI Accelerator repo at \`gov-bid-builds/${p.slug}/\`. To split it into its own standalone repo:

## Steps

1. Create the new GitHub repo (private) at \`ColaberryIntern/${p.slug}\` or similar.

2. From inside the Accelerator repo, run the subtree split:

\`\`\`bash
cd /path/to/colaberry-enterprise-ai-accelerator
git subtree split --prefix=gov-bid-builds/${p.slug} -b ${p.slug}-split
\`\`\`

3. Push the split branch to the new repo:

\`\`\`bash
git remote add ${p.slug}-remote git@github.com:ColaberryIntern/${p.slug}.git
git push ${p.slug}-remote ${p.slug}-split:main
\`\`\`

4. (Optional) Remove the project from the parent repo:

\`\`\`bash
git rm -rf gov-bid-builds/${p.slug}
git commit -m "Split ${p.slug} into own repo"
\`\`\`

5. In the new repo, update README links and CI to point at the new location.

## What stays with the Accelerator

- The BC todo lists in Gov Contracts BC project (proposal + build)
- The Opportunity Pulse opportunity record + uploaded RFP files
- The original requirements.md and architect spec
- The Mandrill email history

## What goes to the new repo

- All source code under \`gov-bid-builds/${p.slug}/\`
- CI / CD configs
- The demo deploy at https://${p.demoDomain}

## When to split

Split once the project is **post-sprint stable** — i.e., the proposal has been submitted and the build is in production / iteration mode. During the 2-week sprint, the project lives in the Accelerator repo so deploys go through the existing pipeline.
`;
}

function requirementsPlaceholder(p) {
  return `# ${p.title} — Requirements

> This file is replaced once the AI Project Architect spec finishes generating.
> Job is running at: https://advisor.colaberry.ai/api/v1/generate/${p.slug.replace(/-/g, '-')}-colaberry-build/status
>
> Run \`node backend/src/scripts/pollArchitectSpecs.js\` from the parent repo
> to download the completed spec into this folder.
`;
}

for (const p of PROJECTS) {
  const dir = path.join(BUILDS_DIR, p.slug);
  fs.writeFileSync(path.join(dir, 'README.md'), readme(p));
  fs.writeFileSync(path.join(dir, 'SETUP.md'), setup());
  fs.writeFileSync(path.join(dir, 'MOVE_TO_OWN_REPO.md'), moveToOwnRepo(p));
  fs.writeFileSync(path.join(dir, '.env.example'), envExample(p));
  fs.writeFileSync(path.join(dir, 'package.json'), packageJson(p));
  fs.writeFileSync(path.join(dir, '.gitignore'), gitignore());
  fs.writeFileSync(path.join(dir, 'requirements.md'), requirementsPlaceholder(p));
  fs.writeFileSync(path.join(dir, 'seeds', 'index.js'), seedIndex(p));
  fs.writeFileSync(path.join(dir, 'app', '.gitkeep'), '');
  fs.writeFileSync(path.join(dir, 'docs', '.gitkeep'), '');
  fs.writeFileSync(path.join(dir, 'deploy', '.gitkeep'), '');
  console.log(`scaffolded ${p.slug}/`);
}

// Top-level README
fs.writeFileSync(path.join(BUILDS_DIR, 'README.md'), `# Gov-bid Build Projects

Working pilots accompanying our 4 active government RFP responses. Each project is a self-contained subfolder that can later be split into its own git repo (see \`MOVE_TO_OWN_REPO.md\` in each).

## Active builds

${PROJECTS.map((p) => `- [\`${p.slug}/\`](./${p.slug}/) — **${p.title}** (${p.agency}). Owner: ${p.intern}. Closes: ${p.closeDate}.`).join('\n')}

## Workflow

1. Each project has a proposal track (in Gov Contracts BC) and a build track (also in Gov Contracts BC, separate list).
2. The build BC list has both human tasks (assigned to the intern) and AI tasks (assigned to CB System, but every AI task needs human approval).
3. The 2-week sprint goal: working pilot deployed to public URL + proposal submitted to the agency, with the proposal narrative referencing the live demo URL.

## Repo structure

\`\`\`
gov-bid-builds/
  <project-slug>/
    README.md           ← project overview
    SETUP.md            ← run locally
    requirements.md     ← AI Project Architect spec
    MOVE_TO_OWN_REPO.md ← split-out instructions
    package.json
    .env.example
    .gitignore
    app/                ← all source code
    seeds/              ← fake-data seeders
    docs/               ← demo screenshots + agency-facing artifacts
    deploy/             ← Docker + deploy scripts
\`\`\`
`);

console.log(`\nScaffold complete. ${PROJECTS.length} projects under ${BUILDS_DIR}`);
