/**
 * Pure rendering helpers for launch-PMO task descriptions.
 *
 * Extracted out of generateLaunchTasks.js so the description HTML — and the
 * dependency-link resolution in particular — can be unit-tested without the
 * script's import-time file reads or its live Basecamp IIFE. All functions
 * here are pure: they take the vault map as an argument and return strings /
 * plain objects. No I/O, no module-level state.
 *
 * F5 fix: "Dependencies" used to render as plain free text, so a dependency
 * like "Ali decisions brief" pointed at nothing clickable. `linkifyDependencies`
 * now hyperlinks any dependency fragment that resolves to a known vault brief
 * (same source of truth as "Briefs to read first") and reports the fragments
 * that resolved to nothing, so the generator can surface unlinked dependencies
 * instead of emitting them silently.
 */

/**
 * Build the "Briefs to read first" <li> list from an array of brief slugs.
 * Unchanged behavior from the original generateLaunchTasks.js; now takes the
 * vault map explicitly instead of closing over a module global.
 */
function buildBriefLinks(slugs, vaultMap) {
  const briefs = (vaultMap && vaultMap.briefs) || {};
  return (slugs || [])
    .map((s) => briefs[s])
    .filter(Boolean)
    .map((b) => `<li><a href="${b.url}">${b.description || b.filename}</a> <span style="color:#94a3b8;font-size:11px">(${b.filename})</span></li>`)
    .join('');
}

/**
 * Turn a free-text dependencies string into HTML where any fragment that maps
 * to a known vault brief becomes a link, and collect the fragments that didn't.
 *
 * Matching is conservative (substring on slug / filename / description, case-
 * insensitive) so we never invent a link for an unrelated phrase. A fragment
 * like "Capacity analysis results" — which corresponds to no brief — is left
 * as plain text and reported in `unlinked`.
 *
 * @returns {{ html: string, unlinked: string[] }}
 */
function linkifyDependencies(depText, vaultMap) {
  const raw = (depText == null ? '' : String(depText)).trim();
  if (!raw || raw.toLowerCase() === 'none') {
    return { html: raw || 'none', unlinked: [] };
  }

  const briefs = (vaultMap && vaultMap.briefs) || {};
  const entries = Object.entries(briefs)
    .map(([key, b]) => ({
      url: b && b.url,
      filename: (b && b.filename) || '',
      slug: (b && b.slug) || key,
      description: (b && b.description) || '',
    }))
    .filter((e) => e.url);

  // Split on the separators a model is likely to use between distinct deps.
  // Deliberately NOT splitting on " and " — too many briefs contain it
  // ("Brand and pricing") and we'd shred a single dependency.
  const fragments = raw.split(/\s*[;,\n]\s*/).map((f) => f.trim()).filter(Boolean);

  const unlinked = [];
  const htmlFragments = fragments.map((frag) => {
    const lower = frag.toLowerCase();
    const match = entries.find((e) =>
      (e.slug && lower.includes(String(e.slug).toLowerCase())) ||
      (e.filename && lower.includes(String(e.filename).toLowerCase())) ||
      (e.description && lower.includes(String(e.description).toLowerCase()))
    );
    if (match) {
      return `<a href="${match.url}">${frag}</a>`;
    }
    unlinked.push(frag);
    return frag;
  });

  return { html: htmlFragments.join(', '), unlinked };
}

/**
 * Build the full task description HTML.
 *
 * @returns {{ html: string, unlinkedDependencies: string[] }} — html to post,
 *   plus the dependency fragments that resolved to no brief link (for the
 *   generator to log).
 */
function buildDescription({ task, ownerLabel, today, vaultMap }) {
  const tierBadge = task.tier === 'ai'
    ? '<span style="background:#dbeafe;color:#1e40af;font-weight:700;font-size:11px;padding:2px 8px;border-radius:3px;letter-spacing:1px">AI TASK</span>'
    : '<span style="background:#fef3c7;color:#92400e;font-weight:700;font-size:11px;padding:2px 8px;border-radius:3px;letter-spacing:1px">HUMAN TASK</span>';
  const recipeBlock = task.claude_code_recipe
    ? `<h3>How to do this in Claude Code</h3><p>${task.claude_code_recipe.replace(/\n/g, '<br>')}</p>`
    : '';
  const links = buildBriefLinks(task.relevant_brief_slugs, vaultMap);
  const dep = linkifyDependencies(task.dependencies, vaultMap);
  const folderLink = vaultMap && vaultMap.folder && vaultMap.folder.url
    ? `<p style="font-size:11px;color:#64748b">All briefs: <a href="${vaultMap.folder.url}">Launch Briefs vault folder</a></p>`
    : '';
  const html = `<div>
${tierBadge} <strong>Owner:</strong> ${ownerLabel}
<h3>Objective</h3>
<p>${task.objective}</p>
<h3>Deliverable</h3>
<p>${task.deliverable}</p>
<h3>Definition of done</h3>
<p>${task.definition_of_done}</p>
<h3>Dependencies</h3>
<p>${dep.html}</p>
${recipeBlock}
<h3>Briefs to read first</h3>
<ul>${links}</ul>
${folderLink}
<p style="font-size:11px;color:#64748b">Generated by CB System Launch PMO on ${today}. Source briefs above. Tag <code>@CB System</code> to escalate or ask for AI execution.</p>
</div>`;

  return { html, unlinkedDependencies: dep.unlinked };
}

module.exports = { buildBriefLinks, linkifyDependencies, buildDescription };
