import { REESE_BEHAVIOURS, type ReeseBehaviourRow } from './reeseBehaviourInventory';

function row(r: ReeseBehaviourRow): string {
  const noteLine = r.note ? `\n\n  Note: ${r.note}` : '';
  return `### ${r.name}\n\n- Controller: ${r.controller}\n- Kill switch: ${r.killSwitch}\n- Population: ${r.population}${noteLine}`;
}

export function renderReeseBehaviourInventoryMarkdown(): string {
  const header =
    '# Reese behaviour inventory\n\n' +
    'R2 of the Reese Product Phase 1 plan. Generated by ' +
    '`backend/src/scripts/generateReeseBehaviourInventory.ts` from ' +
    '`backend/src/scripts/lib/reeseBehaviourInventory.ts` -- never hand-edited. ' +
    'Every real Reese behaviour, its controller, its kill switch, and the population ' +
    'rule as it actually is today, not as documented elsewhere.\n\n' +
    'Two Reese-only switch gaps closed this phase (R2): the reactive reply path and the ' +
    'welcome-DM path now both also stop when `ai_agents.enabled` is false for Reese\'s own ' +
    'row -- previously only the four cron rows honoured `enabled` at all. No switch is ' +
    'turned off in production by this change: R0\'s baseline shows `enabled: true` and the ' +
    'welcome flag `true`, so both new checks pass through live unchanged.';

  const body = REESE_BEHAVIOURS.map(row).join('\n\n');
  return `${header}\n\n${body}\n`;
}
