import { REESE_TOOL_INVENTORY, type ReeseToolRow } from './reeseToolInventory';

function row(r: ReeseToolRow): string {
  const gapLine = r.gap ? `\n- Gap: ${r.gap}` : '';
  return (
    `### ${r.name}\n\n` +
    `- Kind: ${r.kind === 'llm_tool' ? 'LLM-invoked tool' : 'side effect'}\n` +
    `- Source: ${r.source}\n` +
    `- Reads: ${r.reads}\n` +
    `- Produces: ${r.produces}\n` +
    `- Authorization today: ${r.authorization}\n` +
    `- Logging: ${r.logging}${gapLine}`
  );
}

export function renderReeseToolInventoryMarkdown(): string {
  const header =
    '# Reese tool and side-effect inventory\n\n' +
    'R3 of the Reese Product Phase 1 plan. Generated by ' +
    '`backend/src/scripts/generateReeseToolInventory.ts` from ' +
    '`backend/src/scripts/lib/reeseToolInventory.ts` -- never hand-edited. Every real ' +
    'Reese tool and side effect (DM, ticket write, escalation, status change, LLM call), ' +
    'its authorization state today (none, shadow, enforced), and its logging state.\n\n' +
    'This phase makes no authorization change of any kind (execution contract hard stop: ' +
    '"Phase 1 adds no new authority"). Every gap named below, `read_attachments` among ' +
    'them, is Phase 2\'s to fix -- named here so Phase 2 starts from a complete, honest map ' +
    'rather than rediscovering them.';

  const body = REESE_TOOL_INVENTORY.map(row).join('\n\n');
  return `${header}\n\n${body}\n`;
}
