import { ApprovalRequest } from '../../models';
import { authorizeAgentAction } from '../agentAuthorizationService';

// ProofDesk Governance — Milestone 4 (Governance Enforcement, SHADOW MODE ONLY).
//
// This is the ONLY place ProofDesk calls the pre-existing, already-shipped
// authorizeAgentAction() chokepoint (agentAuthorizationService.ts, TBI P2-1, PR #69).
// It is a thin, ProofDesk-specific wrapper — never a second, competing
// implementation of the chokepoint itself.
//
// SHADOW MODE INVARIANT (non-negotiable, per this run's execution contract): this
// function's return value is advisory only. Its caller (ticketAgentDispatcher.ts,
// T006) MUST proceed with the real action exactly as it would have before this
// milestone, regardless of what this function returns. Nothing in this file ever
// throws to block a caller, and nothing in this file's return shape contains a field
// meant to be read as "stop." It exists to LOG a decision, not to make one.
//
// Correlation design: authorization is evaluated BEFORE the real action runs (the
// conventional "gate ahead of the action," even in shadow/log-only mode), but the
// work_ledger_events row for that action isn't written until AFTER it completes
// (success/failure is only known then — see ticketAgentDispatcher.ts). To correlate
// the two without a second write, the CALLER pre-generates the ledger event's UUID
// and passes it here as `eventId` — the same id it will later pass to
// workLedgerService.emitEvent()'s new (Milestone 4) optional `eventId` field. This
// keeps approval_requests.event_id pointed at the ledger event's REAL primary key,
// so T002's existing unique index on event_id is the only idempotency mechanism
// needed here — no second, competing dedup key was introduced.
//
// Failure-First Design (root CLAUDE.md):
// 1. What happens if this fails? Degrades to a safe would_allow default with no
//    approval_requests row — the caller's real action still proceeds unmodified.
// 2. Retry? None automatic — a single fire-once call per dispatch attempt. Because the
//    caller regenerates a fresh eventId per dispatch attempt (same lifecycle as its
//    own idempotency key), a retried dispatch is a fresh evaluation, not a duplicate
//    write against the same event_id.
// 3. Recovery if exhausted? None needed — a missing approval_requests row for one
//    decision only under-documents that one decision in the shadow dashboard; it
//    never blocks or loses the real action.
// 4. Explicit failure modes handled: authorizeAgentAction() throwing (caught, safe
//    default returned), a duplicate event_id on the approval_requests write
//    (findOrCreate — idempotent, returns the existing row, not a second one).
//    Not handled: DB fully unavailable for the approval_requests write — degrades the
//    same way as any other caught error here (safe default, no row).

export interface AuthorizeTicketDispatchInput {
  /** Pre-generated by the caller; the SAME id it will pass to emitEvent()'s
   * eventId field for the ledger event this decision belongs to. */
  eventId: string;
  ticketId: string;
  workUnitId?: string | null;
  runId?: string | null;
  agentName: string;
  action: string;
  riskTier?: string | null;
  /** Real-enforcement scoping, Phase 1 (2026-09-20) — enough real detail to
   * replay the held action later (see approvalRequestReplayService.ts). Optional
   * and backward-compatible: every existing caller that doesn't pass one keeps
   * creating rows exactly as before, just with prepared_action left null (which
   * the replay executor already treats as an honest "nothing to replay" case). */
  preparedAction?: Record<string, any> | null;
}

// Real-enforcement scoping, Phase 1 (2026-09-20) — how long a held action waits
// for a real human decision before the auto-approve-timeout job (R38) releases
// it on its own. 4 hours: grounded in Reese's own real autonomous-outreach sweep
// cadence (a periodic daily-scale job, not sub-minute), not an arbitrary guess —
// long enough for a real review, short enough the queue doesn't feel broken.
// A genuinely disclosed default, not something Ali specified — see this run's
// own report if it needs to change.
export const APPROVAL_REVIEW_WINDOW_MS = 4 * 60 * 60 * 1000;

export interface AuthorizeTicketDispatchResult {
  decisionId: string | null;
  verdict: 'would_allow' | 'would_require_approval' | 'would_block';
  reason: string;
}

const SAFE_DEFAULT: AuthorizeTicketDispatchResult = {
  decisionId: null,
  verdict: 'would_allow',
  reason: 'bridge_error',
};

export async function authorizeTicketDispatch(
  input: AuthorizeTicketDispatchInput,
): Promise<AuthorizeTicketDispatchResult> {
  try {
    const result = await authorizeAgentAction({
      agentId: input.agentName,
      agentName: input.agentName,
      action: input.action,
      resourceType: 'ticket',
      resourceId: input.ticketId,
      context: {
        resourceType: 'ticket',
        riskTier: input.riskTier ?? undefined,
      },
    });

    if (!result.wouldDeny) {
      return { decisionId: null, verdict: 'would_allow', reason: result.reason };
    }

    const verdict: AuthorizeTicketDispatchResult['verdict'] = result.requiresApproval
      ? 'would_require_approval'
      : 'would_block';

    // Real-enforcement scoping (Ali: "scope it as a plan, not code that ships
    // yet" → this row-level fix is the safe, zero-risk first slice of that
    // plan). Every row created here was ALWAYS the subset that would_deny —
    // a clean would_allow verdict never reaches this line at all (see the
    // early return above). Every one of these rows is therefore a genuine
    // candidate for human review, not a passive log entry — so it's written
    // as a real, actionable 'pending' row rather than the inert
    // 'shadow_logged' this milestone originally shipped with (see this
    // model's own header comment: "future enforcement-flip milestone" —
    // this IS that milestone's first slice). This is deliberately safe to
    // ship BEFORE anything gates a real action on the outcome: nothing
    // downstream reads `status` yet (see agentActionAuthorizationBridge.ts's
    // own SHADOW MODE INVARIANT above — still true, unchanged by this
    // commit), so a real approve/reject queue can be built and exercised
    // against real decisions now, safely, ahead of any real gating.
    const [row] = await ApprovalRequest.findOrCreate({
      where: { event_id: input.eventId },
      defaults: {
        event_id: input.eventId,
        ticket_id: input.ticketId,
        work_unit_id: input.workUnitId ?? null,
        run_id: input.runId ?? null,
        agent_name: input.agentName,
        action: input.action,
        risk_tier: input.riskTier ?? 'R0',
        autonomy_level: result.level,
        verdict,
        reason_code: result.reason,
        status: 'pending',
        prepared_action: input.preparedAction ?? null,
        expires_at: new Date(Date.now() + APPROVAL_REVIEW_WINDOW_MS),
      } as any,
    });

    return { decisionId: row.id, verdict, reason: result.reason };
  } catch (err: any) {
    console.error(
      JSON.stringify({
        timestamp: new Date().toISOString(),
        level: 'error',
        service: 'agentActionAuthorizationBridge',
        event: 'authorize_ticket_dispatch_failed',
        outcome: 'failure',
        error_class: err?.name || 'Error',
        context: { ticket_id: input.ticketId, agent_name: input.agentName, action: input.action, message: err?.message },
      }),
    );
    return SAFE_DEFAULT;
  }
}
