/**
 * Model Association Tests
 * Validates that all Sequelize associations are properly defined.
 * Imports models/index.ts to trigger association setup, then inspects model metadata.
 */

// Mock database connection — use postgres dialect but don't actually connect
jest.mock('../../config/database', () => {
  const { Sequelize } = require('sequelize');
  const sequelize = new Sequelize('postgres://mock:mock@localhost:5432/mock', {
    dialect: 'postgres',
    logging: false,
  });
  return { sequelize, connectDatabase: jest.fn() };
});

// Mock env to prevent errors on import
jest.mock('../../config/env', () => ({
  env: {
    databaseUrl: 'postgres://mock:mock@localhost:5432/mock',
    nodeEnv: 'test',
    jwtSecret: 'test-secret',
    port: 3000,
  },
}));

// Import models after mocking — this triggers association setup
import * as Models from '../../models';

describe('Model Associations', () => {
  // Helper to check if a model has an association
  function hasAssociation(model: any, alias: string): boolean {
    return model.associations && alias in model.associations;
  }

  function getAssociationNames(model: any): string[] {
    return Object.keys(model.associations || {});
  }

  describe('Core Curriculum Associations', () => {
    test('CurriculumModule has lessons', () => {
      expect(hasAssociation(Models.CurriculumModule, 'lessons')).toBe(true);
    });

    test('CurriculumLesson belongs to module', () => {
      expect(hasAssociation(Models.CurriculumLesson, 'module')).toBe(true);
    });

    test('CurriculumLesson has miniSections', () => {
      expect(hasAssociation(Models.CurriculumLesson, 'miniSections')).toBe(true);
    });

    test('CurriculumLesson has artifactDefinitions', () => {
      expect(hasAssociation(Models.CurriculumLesson, 'artifactDefinitions')).toBe(true);
    });

    test('CurriculumLesson has sectionConfig', () => {
      expect(hasAssociation(Models.CurriculumLesson, 'sectionConfig')).toBe(true);
    });

    test('CurriculumLesson has associatedSession', () => {
      expect(hasAssociation(Models.CurriculumLesson, 'associatedSession')).toBe(true);
    });
  });

  describe('Program Blueprint Associations', () => {
    test('ProgramBlueprint has modules', () => {
      expect(hasAssociation(Models.ProgramBlueprint, 'modules')).toBe(true);
    });

    test('ProgramBlueprint has cohorts', () => {
      expect(hasAssociation(Models.ProgramBlueprint, 'cohorts')).toBe(true);
    });

    test('ProgramBlueprint has variableDefinitions', () => {
      expect(hasAssociation(Models.ProgramBlueprint, 'variableDefinitions')).toBe(true);
    });
  });

  describe('LiveSession Associations', () => {
    test('LiveSession has gates', () => {
      expect(hasAssociation(Models.LiveSession, 'gates')).toBe(true);
    });

    test('LiveSession has checklist', () => {
      expect(hasAssociation(Models.LiveSession, 'checklist')).toBe(true);
    });

    test('LiveSession has sectionConfigs', () => {
      expect(hasAssociation(Models.LiveSession, 'sectionConfigs')).toBe(true);
    });

    test('LiveSession has artifactDefinitions', () => {
      expect(hasAssociation(Models.LiveSession, 'artifactDefinitions')).toBe(true);
    });

    test('LiveSession has associatedLessons', () => {
      expect(hasAssociation(Models.LiveSession, 'associatedLessons')).toBe(true);
    });
  });

  describe('PromptTemplate Inverse Associations', () => {
    test('PromptTemplate has suggestedSectionConfigs', () => {
      expect(hasAssociation(Models.PromptTemplate, 'suggestedSectionConfigs')).toBe(true);
    });

    test('PromptTemplate has mentorSectionConfigs', () => {
      expect(hasAssociation(Models.PromptTemplate, 'mentorSectionConfigs')).toBe(true);
    });

    test('PromptTemplate has conceptMiniSections', () => {
      expect(hasAssociation(Models.PromptTemplate, 'conceptMiniSections')).toBe(true);
    });

    test('PromptTemplate has buildMiniSections', () => {
      expect(hasAssociation(Models.PromptTemplate, 'buildMiniSections')).toBe(true);
    });

    test('PromptTemplate has mentorMiniSections', () => {
      expect(hasAssociation(Models.PromptTemplate, 'mentorMiniSections')).toBe(true);
    });

    test('PromptTemplate has autoGeneratedArtifacts', () => {
      expect(hasAssociation(Models.PromptTemplate, 'autoGeneratedArtifacts')).toBe(true);
    });

    test('PromptTemplate has instructedArtifacts', () => {
      expect(hasAssociation(Models.PromptTemplate, 'instructedArtifacts')).toBe(true);
    });
  });

  describe('ArtifactDefinition Associations', () => {
    test('ArtifactDefinition has gates (inverse)', () => {
      expect(hasAssociation(Models.ArtifactDefinition, 'gates')).toBe(true);
    });

    test('ArtifactDefinition has submissions', () => {
      expect(hasAssociation(Models.ArtifactDefinition, 'submissions')).toBe(true);
    });

    test('ArtifactDefinition belongs to session', () => {
      expect(hasAssociation(Models.ArtifactDefinition, 'session')).toBe(true);
    });

    test('ArtifactDefinition belongs to lesson', () => {
      expect(hasAssociation(Models.ArtifactDefinition, 'lesson')).toBe(true);
    });

    test('ArtifactDefinition belongs to instructionPrompt', () => {
      expect(hasAssociation(Models.ArtifactDefinition, 'instructionPrompt')).toBe(true);
    });
  });

  describe('Enrollment Associations', () => {
    test('Enrollment has variables with cascade', () => {
      expect(hasAssociation(Models.Enrollment, 'variables')).toBe(true);
    });

    test('Enrollment has submissions', () => {
      expect(hasAssociation(Models.Enrollment, 'submissions')).toBe(true);
    });

    test('Enrollment has lessonInstances', () => {
      expect(hasAssociation(Models.Enrollment, 'lessonInstances')).toBe(true);
    });

    test('Enrollment has skillMasteries', () => {
      expect(hasAssociation(Models.Enrollment, 'skillMasteries')).toBe(true);
    });
  });

  describe('SessionGate Bidirectional', () => {
    test('SessionGate belongs to artifactDefinition', () => {
      expect(hasAssociation(Models.SessionGate, 'artifactDefinition')).toBe(true);
    });

    test('SessionGate belongs to session', () => {
      expect(hasAssociation(Models.SessionGate, 'session')).toBe(true);
    });

    test('SessionGate belongs to module', () => {
      expect(hasAssociation(Models.SessionGate, 'module')).toBe(true);
    });

    test('SessionGate belongs to lesson', () => {
      expect(hasAssociation(Models.SessionGate, 'lesson')).toBe(true);
    });
  });

  describe('MiniSection Associations', () => {
    test('MiniSection belongs to lesson', () => {
      expect(hasAssociation(Models.MiniSection, 'lesson')).toBe(true);
    });

    test('MiniSection belongs to conceptPrompt', () => {
      expect(hasAssociation(Models.MiniSection, 'conceptPrompt')).toBe(true);
    });

    test('MiniSection belongs to buildPrompt', () => {
      expect(hasAssociation(Models.MiniSection, 'buildPrompt')).toBe(true);
    });

    test('MiniSection belongs to mentorPrompt', () => {
      expect(hasAssociation(Models.MiniSection, 'mentorPrompt')).toBe(true);
    });
  });

  describe('VariableStore Associations', () => {
    test('VariableStore belongs to enrollment', () => {
      expect(hasAssociation(Models.VariableStore, 'enrollment')).toBe(true);
    });

    test('VariableStore belongs to definition', () => {
      expect(hasAssociation(Models.VariableStore, 'definition')).toBe(true);
    });
  });

  describe('All models are exported', () => {
    const expectedModels = [
      'Cohort', 'Enrollment', 'AdminUser', 'Lead', 'LiveSession',
      'CurriculumModule', 'CurriculumLesson', 'LessonInstance',
      'SessionGate', 'PromptTemplate', 'SectionConfig',
      'ArtifactDefinition', 'VariableStore', 'SkillMastery',
      'SkillDefinition', 'ProgramBlueprint', 'MiniSection',
      'VariableDefinition', 'SessionChecklist', 'MentorConversation',
    ];

    test.each(expectedModels)('should export %s', (modelName) => {
      expect((Models as any)[modelName]).toBeDefined();
    });
  });
});
