import React from 'react';
import { StoryVerificationState } from './useStoryVerification';

/**
 * StoryCompletionPanel — the completion gate, and the moment it opens.
 *
 * COMPLETION IS GRANTED, NEVER CLAIMED. The only thing that unlocks the button
 * is `verified_at`, a one-way latch the platform stamps after reading the repo.
 * The server already refuses a client-set `complete` with a 409, so an enabled
 * button before verification would be an invitation to a rejected request.
 *
 * A DISABLED BUTTON MUST SAY WHY. A student staring at a dead grey control can
 * see that something is wrong and has no idea what, which is worse than the
 * button not being there. So the panel above it names the outstanding criteria
 * verbatim from the published plan, plus the missing commit — the two halves of
 * the rule fail independently and are reported independently.
 *
 * Amber rather than red throughout: nothing has gone wrong, the work is simply
 * not finished yet, and a red panel would read as an error the student caused.
 */
export interface StoryCompletionPanelProps {
  verif: StoryVerificationState;
  storyKey: string;
  /** The student has already filed this away locally; the panel steps aside. */
  locallyDone: boolean;
  onMarkDone: () => void;
  onSkip: () => void;
}

/**
 * Demo Prep tasks are the student's own work, not the build's.
 *
 * PREP-1..PREP-6 are rehearsals, recordings and the Demo Day slot itself. They
 * are generated by `prepTasks()` with `acceptance: []` and never enter the
 * published plan, so the verifier's spec list has no entry for them and
 * `verified_at` can never be stamped. Gating them on repo verification left
 * every one of them dead: across the whole cohort, 150 of 150 prep tasks sat
 * unverified with no path forward, while the panel told students to push a
 * commit that nothing would ever read. The task's own build prompt already says
 * "This one is you, not Claude Code" — this is the completion gate agreeing.
 *
 * Matched on the id rather than a release flag because the id is what the
 * generator hardcodes and what the panel already receives.
 */
export function isSelfDirectedStory(storyKey: string): boolean {
  return /^PREP-\d+$/i.test((storyKey || '').trim());
}

const StoryCompletionPanel: React.FC<StoryCompletionPanelProps> = ({
  verif, storyKey, locallyDone, onMarkDone, onSkip,
}) => {
  const verified = Boolean(verif.verifiedAt);
  /* Self-directed only while unverified: if one of these ever does get a
     verdict, the normal verified path still wins. */
  const selfDirected = !verified && isSelfDirectedStory(storyKey);

  return (
    <>
      {/* THE MOMENT. Rendered only on a transition the page actually witnessed —
          `phase` reaches 'verified' exclusively when this story crossed the line
          while open. Re-opening a finished story shows the header pill, not a
          re-enactment of something that happened last week. */}
      {verif.phase === 'verified' && (
        <div className="rt-verified" role="status">
          <span className="rt-verified-mark" aria-hidden="true">✓</span>
          <div>
            <div className="rt-verified-t">Verified from your repo</div>
            <div className="rt-verified-s">
              {verif.view?.verification?.commit_sha
                ? <>Confirmed against commit <code>{verif.view.verification.commit_sha.slice(0, 7)}</code>.</>
                : <>Every criterion confirmed, and a commit names this story.</>}
            </div>
          </div>
          {/* Points appear only when there are points. The award is a share of
              the capstone's 800 XP budget and fails closed at 0 if the config
              row is missing, so "+0 XP" would announce an award that did not
              happen. */}
          {verif.xpAwarded > 0 && <span className="rt-verified-xp">+{verif.xpAwarded} XP</span>}
        </div>
      )}

      {!locallyDone && (
        <div style={{ marginTop: 16 }}>
          {!selfDirected && !verified && verif.loaded && verif.missing.length > 0 && (
            <div className="rt-waiting">
              <div className="rt-waiting-h">
                Waiting on GitHub to confirm {verif.missing.length === 1 ? '1 thing' : `${verif.missing.length} things`}
              </div>
              <ul className="rt-waiting-l">
                {verif.missing.map((m, i) => <li key={i}>{m}</li>)}
              </ul>
            </div>
          )}

          {/* THE FILE COULD NOT BE READ. Rendered ahead of everything else and
              in place of it: while this is set the outstanding list is the last
              verdict we could reach, not an answer about the push that just
              landed, and showing it tells a student their criteria failed when
              the truth is we could not see them. That mistake cost one student
              an evening re-verifying code that was already correct.

              Not "tell your instructor" — this is a file in their repo, and the
              sentence from the server names exactly what to change. */}
          {!selfDirected && !verified && verif.readError && (
            <div className="rt-waiting">
              <div className="rt-waiting-h">We could not read your progress file</div>
              <p className="rt-waiting-p">{verif.readError}</p>
              <p className="rt-waiting-p">
                Nothing you have already finished is affected — verification is recorded here on the
                platform, so anything confirmed before this stays confirmed.
              </p>
            </div>
          )}

          {!selfDirected && !verified && verif.blockedReason && (
            <div className="rt-waiting">
              <div className="rt-waiting-h">This story cannot be verified automatically</div>
              <p className="rt-waiting-p">{verif.blockedReason} Tell your instructor.</p>
            </div>
          )}

          {/* Self-directed: say plainly that nobody is coming to check, so the
              student is not left waiting on a confirmation that never arrives. */}
          {selfDirected && (
            <div className="rt-waiting">
              <div className="rt-waiting-h">You confirm this one yourself</div>
              <p className="rt-waiting-p">
                This is a rehearsal step rather than code, so the platform does not check it from
                your repo. When you have done it, mark it done here.
              </p>
            </div>
          )}

          {/* Never checked — say which, rather than showing a locked control with
              no explanation while the platform has simply never looked. */}
          {!selfDirected && !verified && verif.loaded && !verif.view?.verification && !verif.blockedReason && (
            <div className="rt-waiting">
              <div className="rt-waiting-h">Not checked yet</div>
              <p className="rt-waiting-p">
                Connect your repo and push a commit naming {storyKey}. The platform reads
                <code> .colaberry/progress.json</code> and your commits, then confirms this story itself.
              </p>
            </div>
          )}

          <div className="rt-row">
            <button
              className="rt-btn cta"
              disabled={!verified && !selfDirected}
              aria-disabled={!verified && !selfDirected}
              title={
                verified || selfDirected
                  ? undefined
                  : 'Unlocks once the platform confirms this story from your repo'
              }
              onClick={() => { if (verified || selfDirected) onMarkDone(); }}
            >
              {verified || selfDirected ? 'Mark done' : 'Mark done — waiting on GitHub'}
            </button>
            {/* Skipping a story the platform just verified makes no sense — the
                work is done and the credit is already banked. */}
            {!verified && <button className="rt-btn" onClick={onSkip}>Skip</button>}
          </div>
        </div>
      )}
    </>
  );
};

export default StoryCompletionPanel;
