/**
 * F5: launch-PMO task descriptions must resolve dependency references to real
 * vault-brief links and report dependencies that resolve to nothing.
 */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const {
  buildDescription,
  linkifyDependencies,
  buildBriefLinks,
} = require('../../scripts/lib/launchPmoDescription');

const VAULT_MAP = {
  folder: { url: 'https://3.basecamp.com/x/vaults/folder', title: 'Launch Briefs' },
  briefs: {
    'ali-decisions': {
      filename: '19-ali-decisions.md',
      slug: 'ali-decisions',
      url: 'https://3.basecamp.com/x/uploads/19',
      description: 'Ali Executive Sponsor Decisions',
    },
    'kes-ai-systems': {
      filename: '10-kes-ai-systems.md',
      slug: 'kes-ai-systems',
      url: 'https://3.basecamp.com/x/uploads/10',
      description: 'Kes AI Systems',
    },
  },
};

describe('linkifyDependencies', () => {
  it('links a fragment that matches a brief slug', () => {
    const { html, unlinked } = linkifyDependencies('See ali-decisions before deciding', VAULT_MAP);
    expect(html).toContain('<a href="https://3.basecamp.com/x/uploads/19">');
    expect(unlinked).toEqual([]);
  });

  it('links a fragment that matches a brief description (case-insensitive)', () => {
    const { html, unlinked } = linkifyDependencies('kes ai systems design', VAULT_MAP);
    expect(html).toContain('https://3.basecamp.com/x/uploads/10');
    expect(unlinked).toEqual([]);
  });

  it('leaves an unmatched dependency as plain text and reports it', () => {
    const { html, unlinked } = linkifyDependencies('Capacity analysis results', VAULT_MAP);
    expect(html).toBe('Capacity analysis results');
    expect(html).not.toContain('<a ');
    expect(unlinked).toEqual(['Capacity analysis results']);
  });

  it('handles multiple comma/semicolon-separated fragments, mixed matched/unmatched', () => {
    const { html, unlinked } = linkifyDependencies(
      'Capacity analysis results; ali-decisions',
      VAULT_MAP,
    );
    expect(html).toContain('Capacity analysis results');
    expect(html).toContain('<a href="https://3.basecamp.com/x/uploads/19">ali-decisions</a>');
    expect(unlinked).toEqual(['Capacity analysis results']);
  });

  it('returns "none" with no unlinked for empty / none input', () => {
    expect(linkifyDependencies('', VAULT_MAP)).toEqual({ html: 'none', unlinked: [] });
    expect(linkifyDependencies('none', VAULT_MAP)).toEqual({ html: 'none', unlinked: [] });
    expect(linkifyDependencies(null, VAULT_MAP)).toEqual({ html: 'none', unlinked: [] });
  });

  it('does NOT split a single dependency on the word "and"', () => {
    // "and" must not shatter one dependency into two unlinked fragments.
    const { unlinked } = linkifyDependencies('brand and pricing sign-off', VAULT_MAP);
    expect(unlinked).toEqual(['brand and pricing sign-off']);
  });
});

describe('buildBriefLinks', () => {
  it('builds <li> anchors for known slugs and skips unknown ones', () => {
    const html = buildBriefLinks(['ali-decisions', 'does-not-exist'], VAULT_MAP);
    expect(html).toContain('<a href="https://3.basecamp.com/x/uploads/19">');
    expect(html).toContain('(19-ali-decisions.md)');
    expect((html.match(/<li>/g) || []).length).toBe(1);
  });
});

describe('buildDescription', () => {
  const task = {
    tier: 'human',
    objective: 'Confirm cohort cadence and size.',
    deliverable: 'Final decision.',
    definition_of_done: 'Ali confirms.',
    dependencies: 'Capacity analysis results; ali-decisions',
    relevant_brief_slugs: ['ali-decisions'],
    claude_code_recipe: 'step one\nstep two',
  };

  it('embeds linkified dependencies and returns unlinked ones', () => {
    const { html, unlinkedDependencies } = buildDescription({
      task,
      ownerLabel: 'Ali Muwwakkil',
      today: '2026-05-31',
      vaultMap: VAULT_MAP,
    });
    // Dependency that maps to a brief is now a link...
    expect(html).toContain('<a href="https://3.basecamp.com/x/uploads/19">ali-decisions</a>');
    // ...and the one that maps to nothing is reported.
    expect(unlinkedDependencies).toEqual(['Capacity analysis results']);
    // Existing sections still render.
    expect(html).toContain('<strong>Owner:</strong> Ali Muwwakkil');
    expect(html).toContain('<h3>Dependencies</h3>');
    expect(html).toContain('Generated by CB System Launch PMO on 2026-05-31');
    // recipe newlines become <br>
    expect(html).toContain('step one<br>step two');
  });

  it('falls back to "none" when dependencies is empty', () => {
    const { html, unlinkedDependencies } = buildDescription({
      task: { ...task, dependencies: '' },
      ownerLabel: 'X',
      today: '2026-05-31',
      vaultMap: VAULT_MAP,
    });
    expect(html).toContain('<h3>Dependencies</h3>\n<p>none</p>');
    expect(unlinkedDependencies).toEqual([]);
  });
});
