import api from '../utils/api';

/**
 * Measured-metric admin API client.
 *
 * A THIRD SIBLING to `caseStudyAdminApi.ts` (the review desk) and
 * `caseStudyStudioApi.ts` (authoring), matching the backend split exactly: this
 * one drives measurement. Same axios instance, so the same `admin_token`
 * injection and the same 401 bounce apply.
 *
 * WHY THIS EXISTS AT ALL. The admin panel has always read metrics from SNAPSHOT
 * CONTENT, while `resolveChart` resolves against the `case_study_metrics` table.
 * Those are different populations, so a figure the pipeline measured was
 * invisible to every screen in the product. These are the reads and writes for
 * the table.
 *
 * NOTHING HERE MEASURES OR PROMOTES ON ITS OWN. `runMeasurement` asks the server
 * to compute; `promoteMetric` asks it to record a human decision. Both rules
 * live on the server, and this client does not re-implement or pre-empt them —
 * a refusal is rendered, never predicted.
 */

const BASE = '/api/admin/case-studies';

export type MetricVerificationClass = 'verified' | 'anonymized' | 'illustrative' | 'pending';
export type MetricVerificationMethod =
  | 'client' | 'repo' | 'platform' | 'internal' | 'self' | 'manual';

/** One row of `case_study_metrics`, as the measurement panel needs it. */
export interface MeasuredMetric {
  readonly metricKey: string;
  readonly label: string | null;
  readonly valueDisplay: string | null;
  readonly numericValue: number | null;
  readonly unit: string | null;
  readonly metricType: string;
  readonly verificationClass: MetricVerificationClass;
  readonly verificationMethod: MetricVerificationMethod;
  readonly publishable: boolean;
  readonly isHeadline: boolean;
  readonly verifiedBy: string | null;
  readonly verifiedAt: string | null;
  readonly hasEvidence: boolean;
  /** Generated by the run. What a person needs in order to judge the figure. */
  readonly sample: string | null;
  readonly methodology: string | null;
  readonly baseline: string | null;
  readonly limitations: readonly string[];
}

export interface MetricRunReport {
  readonly status: 'written' | 'refused';
  readonly write: {
    readonly status: 'written' | 'refused';
    readonly created?: boolean;
    readonly reason?: string;
    readonly publishedValue?: number | null;
    readonly computedValue?: number | null;
    readonly diverged?: boolean;
    readonly message?: string;
  };
  readonly repoStats: {
    readonly attempted: number;
    readonly analysed: number;
    readonly unreadable: number;
    readonly pinnedDatesFetched: number;
  };
}

export interface PromoteMetricInput {
  readonly verificationClass: MetricVerificationClass;
  readonly publishable: boolean;
  readonly isHeadline: boolean;
}

/** Every figure measured on this record. Empty is a real state, not an error. */
export async function listMeasuredMetrics(caseStudyId: string): Promise<MeasuredMetric[]> {
  const { data } = await api.get<{ metrics: MeasuredMetric[] }>(`${BASE}/${caseStudyId}/metrics`);
  return data.metrics ?? [];
}

/** The definitions the server can run. */
export async function listMetricDefinitions(): Promise<string[]> {
  const { data } = await api.get<{ definitionKeys: string[] }>(`${BASE}/metrics/definitions`);
  return data.definitionKeys ?? [];
}

/**
 * Measure. This spends GitHub quota and writes a row, so it is a deliberate act
 * rather than something a page does on load.
 */
export async function runMeasurement(
  caseStudyId: string, definitionKey: string
): Promise<MetricRunReport> {
  const { data } = await api.post<MetricRunReport>(
    `${BASE}/${caseStudyId}/metrics/run`, { definitionKey }
  );
  return data;
}

/**
 * Record a human decision about a figure.
 *
 * The actor is NOT a parameter. The server takes it from the session, so a
 * caller cannot promote a figure in somebody else's name — and this signature
 * is the client-side half of that, because a field that does not exist here
 * cannot be sent by mistake.
 */
export async function promoteMetric(
  caseStudyId: string, metricKey: string, input: PromoteMetricInput
): Promise<MeasuredMetric> {
  const { data } = await api.post<{ metric: MeasuredMetric }>(
    `${BASE}/${caseStudyId}/metrics/${encodeURIComponent(metricKey)}/promote`, input
  );
  return data.metric;
}
