import AiAgent from '../models/AiAgent';
import type { AiAgentType, AiAgentTriggerType, AiAgentCategory } from '../models/AiAgent';
import { Op } from 'sequelize';

interface AgentSeedEntry {
  agent_name: string;
  agent_type: AiAgentType;
  module: string;
  source_file: string;
  trigger_type: AiAgentTriggerType;
  schedule: string;
  category: AiAgentCategory;
  description: string;
  config?: Record<string, any>;
}

const AGENT_REGISTRY: AgentSeedEntry[] = [
  // --- schedulerService.ts cron jobs ---
  {
    agent_name: 'ScheduledActionsProcessor',
    agent_type: 'scheduled_processor',
    module: 'schedulerService',
    source_file: 'backend/src/services/schedulerService.ts',
    trigger_type: 'cron',
    schedule: '*/5 * * * *',
    category: 'outbound',
    description:
      'Processes pending ScheduledEmail records across all channels (email, voice, SMS). Applies AI content generation at send time, handles test mode overrides, and enforces pacing/rate limits per campaign.',
  },
  {
    agent_name: 'NoShowDetector',
    agent_type: 'scheduled_processor',
    module: 'schedulerService',
    source_file: 'backend/src/services/schedulerService.ts',
    trigger_type: 'cron',
    schedule: '*/15 * * * *',
    category: 'outbound',
    description:
      'Detects strategy calls >30 minutes past scheduled time still marked "scheduled". Marks as no_show, auto-completes CampaignLead, cancels prep nudges, and enrolls lead in recovery sequence.',
  },
  {
    agent_name: 'ICPInsightComputer',
    agent_type: 'insight_computer',
    module: 'schedulerService',
    source_file: 'backend/src/services/icpInsightService.ts',
    trigger_type: 'cron',
    schedule: '0 2 * * *',
    category: 'behavioral',
    description:
      'Computes aggregated ICP insights from 90 days of interaction data. Analyzes by industry, title, company size, and source type. Uses Wilson score confidence intervals. Auto-refreshes active ICP profile stats.',
  },
  {
    agent_name: 'BehavioralSignalDetector',
    agent_type: 'signal_detector',
    module: 'schedulerService',
    source_file: 'backend/src/services/behavioralSignalService.ts',
    trigger_type: 'cron',
    schedule: '*/10 * * * *',
    category: 'behavioral',
    description:
      'Detects 16 buying signal types from PageEvent data on closed visitor sessions. Signals include pricing page visits, enrollment CTA clicks, deep scrolls, form submissions, and multi-category research patterns.',
  },
  {
    agent_name: 'IntentScoreRecomputer',
    agent_type: 'intent_scorer',
    module: 'schedulerService',
    source_file: 'backend/src/services/intentScoringService.ts',
    trigger_type: 'cron',
    schedule: '7,22,37,52 * * * *',
    category: 'behavioral',
    description:
      'Recomputes intent scores for visitors with recent behavioral signals. Uses time-decay weighting (7-day half-life) to prioritize recent activity. Maps to intent levels: low, medium, high, very high.',
  },
  {
    agent_name: 'BehavioralTriggerEvaluator',
    agent_type: 'trigger_evaluator',
    module: 'schedulerService',
    source_file: 'backend/src/services/behavioralTriggerService.ts',
    trigger_type: 'cron',
    schedule: '5,15,25,35,45,55 * * * *',
    category: 'behavioral',
    description:
      'Evaluates behavioral trigger rules and automatically enrolls qualifying leads in behavior-triggered campaigns. Creates CampaignLead records and queues initial outreach actions.',
  },
  {
    agent_name: 'PageEventCleanup',
    agent_type: 'maintenance',
    module: 'schedulerService',
    source_file: 'backend/src/services/schedulerService.ts',
    trigger_type: 'cron',
    schedule: '0 3 * * *',
    category: 'maintenance',
    description:
      'Data retention: deletes PageEvent records older than 90 days to manage database size.',
  },
  {
    agent_name: 'ChatMessageCleanup',
    agent_type: 'maintenance',
    module: 'schedulerService',
    source_file: 'backend/src/services/schedulerService.ts',
    trigger_type: 'cron',
    schedule: '30 3 * * *',
    category: 'maintenance',
    description:
      'Data retention: deletes ChatMessage records older than 180 days to manage database size.',
  },
  {
    agent_name: 'OpportunityScoreRecomputer',
    agent_type: 'opportunity_scorer',
    module: 'schedulerService',
    source_file: 'backend/src/services/opportunityScoringService.ts',
    trigger_type: 'cron',
    schedule: '3,23,43 * * * *',
    category: 'behavioral',
    description:
      'Recomputes opportunity scores for active leads based on behavioral signals, intent scores, ICP alignment, and campaign engagement metrics.',
  },
  {
    agent_name: 'EmailDigest',
    agent_type: 'digest',
    module: 'schedulerService',
    source_file: 'backend/src/services/schedulerService.ts',
    trigger_type: 'cron',
    schedule: '0 * * * *',
    category: 'outbound',
    description:
      'Checks if email digest is enabled. Compiles and sends daily/weekly digest emails at the configured hour and day to admin recipients.',
  },
  {
    agent_name: 'SessionReminders',
    agent_type: 'reminder',
    module: 'schedulerService',
    source_file: 'backend/src/services/schedulerService.ts',
    trigger_type: 'cron',
    schedule: '*/30 * * * *',
    category: 'accelerator',
    description:
      'Sends 24-hour and 1-hour reminder emails to enrolled participants for upcoming live sessions.',
  },
  {
    agent_name: 'SessionLifecycle',
    agent_type: 'session_manager',
    module: 'schedulerService',
    source_file: 'backend/src/services/schedulerService.ts',
    trigger_type: 'cron',
    schedule: '*/5 * * * *',
    category: 'accelerator',
    description:
      'Manages session state transitions: marks sessions as "live" 15 min before start and "completed" 30 min after end. Post-completion: detects absent participants, sends session recaps, and recomputes readiness scores.',
  },
  // --- aiOpsScheduler.ts agents ---
  {
    agent_name: 'CampaignHealthScanner',
    agent_type: 'health_scanner',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/campaignHealthScanner.ts',
    trigger_type: 'cron',
    schedule: '*/15 * * * *',
    category: 'ai_ops',
    description:
      'Scans all active campaigns and computes health scores (0-100) based on channel connectivity, delivery rate, AI generation success, engagement metrics, and error rate. Upserts CampaignHealth records.',
  },
  {
    agent_name: 'CampaignRepairAgent',
    agent_type: 'repair',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/campaignRepairAgent.ts',
    trigger_type: 'cron',
    schedule: '8,28,48 * * * *',
    category: 'ai_ops',
    description:
      'Detects and repairs broken campaign automations. Retries failed ScheduledEmail sends (up to 3 attempts with 30min backoff). Detects stalled campaigns with active leads but no pending actions. Auto-resolves errors older than 7 days.',
    config: {
      auto_retry_enabled: true,
      max_retry_attempts: 3,
      retry_delay_minutes: 30,
      auto_resolve_stale_days: 7,
    },
  },
  {
    agent_name: 'ContentOptimizationAgent',
    agent_type: 'content_optimization',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/contentOptimizationAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'ai_ops',
    description:
      'Detects campaigns with low engagement (open rate <10% or reply rate <1% over 48h) and rewrites pending email subjects and bodies using AI. Rate-limited to 10 rewrites per run with 6-hour cooldown.',
    config: {
      auto_rewrite_enabled: true,
      max_auto_actions_per_hour: 10,
      open_rate_threshold: 0.10,
      reply_rate_threshold: 0.01,
      min_sample_size: 10,
      cooldown_minutes: 360,
    },
  },
  {
    agent_name: 'ConversationOptimizationAgent',
    agent_type: 'conversation_optimization',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/conversationOptimizationAgent.ts',
    trigger_type: 'cron',
    schedule: '0 4 * * *',
    category: 'ai_ops',
    description:
      'Detects step-level conversation dropoffs (>80% reply rate decline between steps) and enhances AI instructions for future sends. Rate-limited to 5 enhancements per run with 24-hour cooldown.',
    config: {
      auto_enhance_enabled: true,
      max_auto_actions_per_hour: 5,
      dropoff_threshold: 0.80,
      min_sent_per_step: 5,
      cooldown_minutes: 1440,
    },
  },
  // --- Orchestration monitoring agents ---
  {
    agent_name: 'OrchestrationHealthAgent',
    agent_type: 'orchestration_health',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/orchestrationHealthAgent.ts',
    trigger_type: 'cron',
    schedule: '*/5 * * * *',
    category: 'accelerator',
    description:
      'Computes orchestration health score (0-100) from curriculum, prompt, artifact, student, and gating checks. Stores time-series snapshots and detects status changes (healthy/degraded/critical).',
  },
  {
    agent_name: 'StudentProgressMonitor',
    agent_type: 'student_monitor',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/studentProgressMonitor.ts',
    trigger_type: 'cron',
    schedule: '*/2 * * * *',
    category: 'accelerator',
    description:
      'Monitors active enrollments for stuck students (>48h on a lesson), missing required artifacts, and gating deadlocks where prerequisites are met but gates remain locked.',
  },
  {
    agent_name: 'PromptMonitorAgent',
    agent_type: 'prompt_monitor',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/promptMonitorAgent.ts',
    trigger_type: 'cron',
    schedule: '*/1 * * * *',
    category: 'accelerator',
    description:
      'Detects inactive prompts still referenced by mini-sections, broken FK references to non-existent prompt templates, and recent prompt execution errors.',
  },
  {
    agent_name: 'OrchestrationAutoRepairAgent',
    agent_type: 'orchestration_repair',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/orchestrationAutoRepairAgent.ts',
    trigger_type: 'cron',
    schedule: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *',
    category: 'accelerator',
    description:
      'Reads recent findings from monitoring agents and applies safe auto-repairs: re-activating inactive prompts still in use, nullifying broken FK references. Max 10 repairs per run.',
    config: {
      max_repairs_per_run: 10,
    },
  },
  // --- Campaign QA & Self-Healing agents ---
  {
    agent_name: 'CampaignQAAgent',
    agent_type: 'campaign_qa',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/campaignQAAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'ai_ops',
    description:
      'Runs end-to-end tests on all active campaigns every 6 hours. Creates test leads, tests email/SMS/voice channels, verifies AI generation, and computes QA scores (0-100).',
  },
  {
    agent_name: 'AutonomousRampEvaluator',
    agent_type: 'scheduled_processor',
    module: 'schedulerService',
    source_file: 'backend/src/services/autonomousRampService.ts',
    trigger_type: 'cron',
    schedule: '0 */2 * * *',
    category: 'outbound',
    description:
      'Evaluates health scores for active autonomous campaigns every 2 hours. Advances ramp phases when health >= 70, holds at 50-69, and pauses for review below 50.',
  },
  {
    agent_name: 'CampaignEvolutionEngine',
    agent_type: 'scheduled_processor',
    module: 'schedulerService',
    source_file: 'backend/src/services/campaignEvolutionService.ts',
    trigger_type: 'cron',
    schedule: '0 */4 * * *',
    category: 'outbound',
    description:
      'Generates and evaluates AI message variants for autonomous campaigns every 4 hours. Creates A/B test variants, scores performance, promotes winners, and retires underperformers.',
  },
  {
    agent_name: 'ApolloLeadIntelligenceAgent',
    agent_type: 'lead_intelligence',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/apolloLeadIntelligenceAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'outbound',
    description:
      'Discovers leads from Apollo using ICP profiles on autonomous campaigns. Creates lead recommendations pending admin approval. Scores program fit (0-100) and estimates ROI.',
    config: {
      max_leads_per_profile: 50,
      min_program_fit_score: 40,
      avg_deal_value: 25000,
    },
  },
  {
    agent_name: 'CampaignSelfHealingAgent',
    agent_type: 'self_healing',
    module: 'aiOpsScheduler',
    source_file: 'backend/src/services/agents/campaignSelfHealingAgent.ts',
    trigger_type: 'cron',
    schedule: '15,45 * * * *',
    category: 'ai_ops',
    description:
      'Detects failures from QA test runs and attempts repairs: retries failed emails, re-triggers SMS/voice, and re-tests after repair. Runs every 30 minutes offset from repair agent.',
    config: {
      auto_heal_enabled: true,
      max_retry_attempts: 3,
    },
  },
  // --- Intelligence Layer Agents (Autonomous Operations) ---
  {
    agent_name: 'ProblemDiscoveryAgent',
    agent_type: 'problem_discovery',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/ProblemDiscoveryAgent.ts',
    trigger_type: 'cron',
    schedule: '5,15,25,35,45,55 * * * *',
    category: 'autonomous',
    description: 'Scans for anomalies, conversion drops, error spikes, and agent failures every 10 minutes.',
  },
  {
    agent_name: 'RootCauseAgent',
    agent_type: 'root_cause',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/RootCauseAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'autonomous',
    description: 'Root cause analysis via activity logs, knowledge graph, and vector memory. On-demand.',
  },
  {
    agent_name: 'ActionPlannerAgent',
    agent_type: 'action_planner',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/ActionPlannerAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'autonomous',
    description: 'Maps root causes to safe executable actions from an allowlist. On-demand.',
  },
  {
    agent_name: 'ImpactEstimatorAgent',
    agent_type: 'impact_estimator',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/ImpactEstimatorAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'autonomous',
    description: 'Predicts metric changes from proposed actions using historical outcomes. On-demand.',
  },
  {
    agent_name: 'RiskEvaluatorAgent',
    agent_type: 'risk_evaluator',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/RiskEvaluatorAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'autonomous',
    description: 'Deterministic risk + confidence scoring for action gating. On-demand.',
  },
  {
    agent_name: 'ExecutionAgent',
    agent_type: 'execution',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/ExecutionAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'autonomous',
    description: 'Execute safe actions with before/after state snapshots. On-demand.',
  },
  {
    agent_name: 'MonitorAgent',
    agent_type: 'monitor',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/MonitorAgent.ts',
    trigger_type: 'cron',
    schedule: '5,15,25,35,45,55 * * * *',
    category: 'autonomous',
    description: 'Track decision outcomes at 1h/6h/24h checkpoints with auto-rollback.',
  },
  {
    agent_name: 'AuditAgent',
    agent_type: 'audit',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/AuditAgent.ts',
    trigger_type: 'cron',
    schedule: '0 1 * * *',
    category: 'autonomous',
    description: 'Daily decision audit with success rate tracking and governance reporting.',
  },
  // --- Strategic Agents ---
  {
    agent_name: 'StrategicIntelligenceAgent',
    agent_type: 'strategic_intelligence',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/StrategicIntelligenceAgent.ts',
    trigger_type: 'cron',
    schedule: '0,30 * * * *',
    category: 'strategic',
    description: 'Cross-entity KPI aggregation and systemic pattern detection.',
  },
  {
    agent_name: 'RevenueOptimizationAgent',
    agent_type: 'revenue_optimization',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/RevenueOptimizationAgent.ts',
    trigger_type: 'cron',
    schedule: '0,30 * * * *',
    category: 'strategic',
    description: 'Lead → enrollment conversion funnel analysis and revenue optimization.',
  },
  {
    agent_name: 'CostOptimizationAgent',
    agent_type: 'cost_optimization',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/CostOptimizationAgent.ts',
    trigger_type: 'cron',
    schedule: '0,30 * * * *',
    category: 'strategic',
    description: 'Agent fleet efficiency analysis and cost optimization.',
  },
  {
    agent_name: 'GrowthExperimentAgent',
    agent_type: 'growth_experiment',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/GrowthExperimentAgent.ts',
    trigger_type: 'cron',
    schedule: '0,30 * * * *',
    category: 'strategic',
    description: 'Propose A/B tests from uncertain recommendations.',
  },
  {
    agent_name: 'GovernanceAgent',
    agent_type: 'governance',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/GovernanceAgent.ts',
    trigger_type: 'cron',
    schedule: '5,15,25,35,45,55 * * * *',
    category: 'strategic',
    description: 'Enforce guardrails: max actions/hour, risk budget, resource caps.',
  },
  // --- Memory Agents ---
  {
    agent_name: 'MemoryAgent',
    agent_type: 'memory',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/memory/vectorMemory.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'memory',
    description: 'Store and retrieve semantic memories via pgvector. On-demand.',
  },
  {
    agent_name: 'KnowledgeGraphAgent',
    agent_type: 'memory',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/knowledge/knowledgeGraph.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'memory',
    description: 'Business entity relationship graph built from DatasetRegistry. On-demand.',
  },
  {
    agent_name: 'LearningAgent',
    agent_type: 'memory',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/memory/learningEngine.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'memory',
    description: 'Updates knowledge and memory from decision outcomes. On-demand.',
  },
  // --- Meta-Agents ---
  {
    agent_name: 'PerformanceAgent',
    agent_type: 'performance_tracker',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/meta/performanceAgent.ts',
    trigger_type: 'cron',
    schedule: '2 * * * *',
    category: 'meta',
    description: 'Aggregate agent performance metrics and detect degrading trends. Hourly.',
  },
  {
    agent_name: 'ArchitectureAgent',
    agent_type: 'architecture_analyzer',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/meta/architectureAgent.ts',
    trigger_type: 'cron',
    schedule: '2 * * * *',
    category: 'meta',
    description: 'Analyze agent fleet for schedule overlaps, idle agents, and error cascades. Hourly.',
  },
  {
    agent_name: 'PromptOptimizationAgent',
    agent_type: 'prompt_optimizer',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/meta/promptOptimizationAgent.ts',
    trigger_type: 'cron',
    schedule: '2 * * * *',
    category: 'meta',
    description: 'Detect weak reasoning patterns and propose prompt improvements. Hourly.',
  },
  {
    agent_name: 'ExperimentAgent',
    agent_type: 'experiment_runner',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/meta/experimentAgent.ts',
    trigger_type: 'cron',
    schedule: '2 * * * *',
    category: 'meta',
    description: 'Controlled experiments with safety guardrails for agent improvement. Hourly.',
  },
  // --- Website Intelligence Agents ---
  {
    agent_name: 'WebsiteUIVisibilityAgent',
    agent_type: 'website_ui',
    module: 'websiteIntelligence',
    source_file: 'backend/src/services/agents/websiteUIVisibilityAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'website_intelligence',
    description:
      'Scans all public pages for accessibility issues: missing alt text, aria-hidden interactive content, unlabeled form fields, and low-contrast text.',
  },
  {
    agent_name: 'WebsiteBrokenLinkAgent',
    agent_type: 'website_links',
    module: 'websiteIntelligence',
    source_file: 'backend/src/services/agents/websiteBrokenLinkAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'website_intelligence',
    description:
      'Crawls all public pages checking internal links against known routes and external links via HEAD requests. Detects empty hrefs, unknown routes, and HTTP errors.',
  },
  {
    agent_name: 'WebsiteConversionFlowAgent',
    agent_type: 'website_conversion',
    module: 'websiteIntelligence',
    source_file: 'backend/src/services/agents/websiteConversionFlowAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */12 * * *',
    category: 'website_intelligence',
    description:
      'Maps CTA destinations per page and validates expected conversion flows. Detects dead-end pages, missing expected paths, and circular navigation loops.',
  },
  {
    agent_name: 'WebsiteUXHeuristicAgent',
    agent_type: 'website_ux',
    module: 'websiteIntelligence',
    source_file: 'backend/src/services/agents/websiteUXHeuristicAgent.ts',
    trigger_type: 'cron',
    schedule: '0 0 * * *',
    category: 'website_intelligence',
    description:
      'Evaluates pages against UX heuristics: form field count, CTA density, heading hierarchy, word count, and content depth.',
  },
  {
    agent_name: 'WebsiteBehaviorAgent',
    agent_type: 'website_behavior',
    module: 'websiteIntelligence',
    source_file: 'backend/src/services/agents/websiteBehaviorAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */12 * * *',
    category: 'website_intelligence',
    description:
      'Analyzes PageEvent data to detect low-traffic pages, form abandonment patterns, and engagement anomalies across the public website.',
  },
  {
    agent_name: 'WebsiteAutoRepairAgent',
    agent_type: 'website_repair',
    module: 'websiteIntelligence',
    source_file: 'backend/src/services/agents/websiteAutoRepairAgent.ts',
    trigger_type: 'event_driven',
    schedule: '',
    category: 'website_intelligence',
    description:
      'Processes open WebsiteIssue records. Routes through COO decision layer: auto-resolves high-confidence (>=0.95), COO approval (0.80-0.94), CEO review (<0.80).',
  },
  {
    agent_name: 'WebsiteImprovementStrategist',
    agent_type: 'website_strategist',
    module: 'websiteIntelligence',
    source_file: 'backend/src/services/agents/websiteImprovementStrategist.ts',
    trigger_type: 'cron',
    schedule: '0 0 * * *',
    category: 'website_intelligence',
    description:
      'Generates strategic improvement recommendations: missing social proof, weak CTA copy, absent trust signals, missing urgency, and SEO gaps.',
  },

  // --- Admissions Intelligence Agents ---
  {
    agent_name: 'AdmissionsVisitorIdentityAgent',
    agent_type: 'admissions_identity',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsVisitorIdentityAgent.ts',
    trigger_type: 'event_driven',
    schedule: '',
    category: 'admissions',
    description: 'Classifies visitor_type on AdmissionsMemory from lead data, email domain, and behavioral signals.',
  },
  {
    agent_name: 'AdmissionsVisitorActivityAgent',
    agent_type: 'admissions_activity',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsVisitorActivityAgent.ts',
    trigger_type: 'cron',
    schedule: '*/10 * * * *',
    category: 'admissions',
    description: 'Enriches PageEvents with admissions context and tags sessions with admissions interest signals.',
  },
  {
    agent_name: 'AdmissionsConversationMemoryAgent',
    agent_type: 'admissions_memory',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsConversationMemoryAgent.ts',
    trigger_type: 'cron',
    schedule: '*/30 * * * *',
    category: 'admissions',
    description: 'Processes closed ChatConversations into AdmissionsMemory summaries for cross-session continuity.',
  },
  {
    agent_name: 'AdmissionsIntentDetectionAgent',
    agent_type: 'admissions_intent',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsIntentDetectionAgent.ts',
    trigger_type: 'cron',
    schedule: '*/10 * * * *',
    category: 'admissions',
    description: 'Applies admissions-specific intent thresholds and updates recommended_next_action on AdmissionsMemory.',
  },
  {
    agent_name: 'AdmissionsConversationPlanningAgent',
    agent_type: 'admissions_planning',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsConversationPlanningAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions',
    description: 'Determines conversation goal and next-message strategy based on visitor type, intent, and memory.',
  },
  {
    agent_name: 'AdmissionsKnowledgeAgent',
    agent_type: 'admissions_knowledge',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsKnowledgeAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions',
    description: 'RAG retrieval from AdmissionsKnowledgeEntry for accurate program information.',
  },
  {
    agent_name: 'AdmissionsProactiveOutreachAgent',
    agent_type: 'admissions_proactive',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsProactiveOutreachAgent.ts',
    trigger_type: 'cron',
    schedule: '*/5 * * * *',
    category: 'admissions',
    description: 'Sets proactive_chat_pending on high-intent visitors without active conversations for Maya outreach.',
  },
  {
    agent_name: 'AdmissionsPageContextAgent',
    agent_type: 'admissions_page_context',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsPageContextAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions',
    description: 'Provides page-specific conversation strategy hints (focus areas, suggested questions).',
  },
  {
    agent_name: 'AdmissionsConversationContinuityAgent',
    agent_type: 'admissions_continuity',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsConversationContinuityAgent.ts',
    trigger_type: 'cron',
    schedule: '*/5 * * * *',
    category: 'admissions',
    description: 'Merges context from short consecutive conversations for the same visitor to detect browsing patterns.',
  },
  {
    agent_name: 'AdmissionsHighIntentLeadAgent',
    agent_type: 'admissions_high_intent',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsHighIntentLeadAgent.ts',
    trigger_type: 'cron',
    schedule: '*/10 * * * *',
    category: 'admissions',
    description: 'Flags enterprise prospects based on corporate email domains, conversation count, and enterprise page visits.',
  },
  {
    agent_name: 'AdmissionsCEORecognitionAgent',
    agent_type: 'admissions_ceo_recognition',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsCEORecognitionAgent.ts',
    trigger_type: 'event_driven',
    schedule: '',
    category: 'admissions',
    description: 'Detects CEO identity via lead email/name, sets visitor_type=ceo, triggers executive greeting.',
  },
  {
    agent_name: 'AdmissionsInsightsAgent',
    agent_type: 'admissions_insights',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsInsightsAgent.ts',
    trigger_type: 'cron',
    schedule: '*/30 * * * *',
    category: 'admissions',
    description: 'Aggregates admissions analytics: visitor types, conversation counts, top interests, intent distribution.',
  },
  {
    agent_name: 'AdmissionsExecutiveUpdateAgent',
    agent_type: 'admissions_executive_update',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/admissionsExecutiveUpdateAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */4 * * *',
    category: 'admissions',
    description: 'Generates executive summary of admissions activity every 4 hours with pipeline metrics and notable conversations.',
  },

  // --- Admissions Operations (10 agents) ---
  {
    agent_name: 'AdmissionsDocumentDeliveryAgent',
    agent_type: 'admissions_document_delivery',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsDocumentDeliveryAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions_ops',
    description: 'Send documents (executive briefing, program overview, enterprise guide, pricing) with workflow stage enforcement.',
  },
  {
    agent_name: 'AdmissionsEmailAgent',
    agent_type: 'admissions_email',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsEmailAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions_ops',
    description: 'Send follow-up emails, materials, appointment confirmations, and admissions updates via SMTP.',
  },
  {
    agent_name: 'AdmissionsSMSAgent',
    agent_type: 'admissions_sms',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsSMSAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions_ops',
    description: 'Send conversation summaries, appointment reminders, and requested links via GoHighLevel SMS.',
  },
  {
    agent_name: 'AdmissionsAppointmentSchedulingAgent',
    agent_type: 'admissions_appointment',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsAppointmentAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions_ops',
    description: 'Schedule admissions and strategy calls via Google Calendar with Appointment record creation.',
  },
  {
    agent_name: 'AdmissionsSynthflowCallAgent',
    agent_type: 'admissions_synthflow_call',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsSynthflowCallAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions_ops',
    description: 'Initiate Synthflow voice calls with mandatory governance approval (24h rule).',
  },
  {
    agent_name: 'AdmissionsCallGovernanceAgent',
    agent_type: 'admissions_call_governance',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsCallGovernanceAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'admissions_ops',
    description: 'Approve or deny voice calls based on 24-hour rule and CallContactLog history.',
  },
  {
    agent_name: 'AdmissionsCallComplianceMonitor',
    agent_type: 'admissions_call_compliance',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsCallComplianceAgent.ts',
    trigger_type: 'cron',
    schedule: '*/15 * * * *',
    category: 'admissions_ops',
    description: 'Detect duplicate outreach, campaign conflicts, and spam patterns in call logs.',
  },
  {
    agent_name: 'AdmissionsCallbackManagementAgent',
    agent_type: 'admissions_callback',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsCallbackAgent.ts',
    trigger_type: 'cron',
    schedule: '*/5 * * * *',
    category: 'admissions_ops',
    description: 'Process pending callback requests, schedule callbacks with governance verification.',
  },
  {
    agent_name: 'AdmissionsConversationTaskMonitor',
    agent_type: 'admissions_task_monitor',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsConversationTaskMonitor.ts',
    trigger_type: 'cron',
    schedule: '*/2 * * * *',
    category: 'admissions_ops',
    description: 'Scan active conversations for action requests (document, callback, email, SMS, appointment).',
  },
  {
    agent_name: 'AdmissionsAssistantAgent',
    agent_type: 'admissions_assistant',
    module: 'admissionsOperations',
    source_file: 'backend/src/services/agents/admissions/admissionsAssistantAgent.ts',
    trigger_type: 'cron',
    schedule: '*/10 * * * *',
    category: 'admissions_ops',
    description: 'Prepare daily call queues, verify eligibility, monitor operational backlog.',
  },
  // --- Cory Product Operations agents (COO → Executive Office) ---
  {
    agent_name: 'CoryStrategicAgent',
    agent_type: 'action_planner',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/CoryStrategicAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'executive',
    description: 'On-demand strategic agent invoked by CoryEngine. Translates natural language commands into structured tickets and action plans.',
  },
  {
    agent_name: 'CurriculumArchitectAgent',
    agent_type: 'curriculum_architect',
    module: 'agents',
    source_file: 'backend/src/services/agents/curriculumArchitectAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'curriculum',
    description: 'Designs curriculum module structures from ticket metadata. Creates modules, lessons, and sub-tickets for artifact generation.',
  },
  {
    agent_name: 'ArtifactGenerationAgent',
    agent_type: 'artifact_generator',
    module: 'agents',
    source_file: 'backend/src/services/agents/artifactGenerationAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'curriculum',
    description: 'Generates teaching artifacts (slides, labs, exercises, assessments) for curriculum lessons using AI content generation.',
  },
  {
    agent_name: 'CurriculumQAAgent',
    agent_type: 'curriculum_qa',
    module: 'agents',
    source_file: 'backend/src/services/agents/curriculumQAAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'curriculum',
    description: 'Validates curriculum integrity by walking lesson sequences, checking content existence, and creating tickets for issues. Every 6 hours.',
  },
  {
    agent_name: 'CurriculumOptimizerAgent',
    agent_type: 'curriculum_optimizer',
    module: 'agents',
    source_file: 'backend/src/services/agents/curriculumOptimizerAgent.ts',
    trigger_type: 'cron',
    schedule: '0 6 * * *',
    category: 'curriculum',
    description: 'Analyzes student behavior data to identify drop-off points, slow lessons, and optimization opportunities. Daily at 6am.',
  },
  {
    agent_name: 'StudentBehaviorIntelligenceAgent',
    agent_type: 'student_behavior_intelligence',
    module: 'agents',
    source_file: 'backend/src/services/agents/studentBehaviorIntelligenceAgent.ts',
    trigger_type: 'cron',
    schedule: '*/30 * * * *',
    category: 'behavioral',
    description: 'Aggregates student navigation events to detect anomalies: high drop-off, idle patterns, unusual mentor usage. Every 30 minutes.',
  },
  {
    agent_name: 'PlatformFixAgent',
    agent_type: 'platform_fix',
    module: 'agents',
    source_file: 'backend/src/services/agents/platformFixAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'maintenance',
    description: 'Diagnoses and fixes platform bugs from ticket descriptions. Confidence-gated: auto-fix for high-confidence/low-risk, diagnostic comment otherwise.',
  },
  {
    agent_name: 'TicketManagementAgent',
    agent_type: 'ticket_management',
    module: 'agents',
    source_file: 'backend/src/services/agents/ticketManagementAgent.ts',
    trigger_type: 'cron',
    schedule: '*/15 * * * *',
    category: 'operations',
    description: 'Auto-assigns unassigned tickets, escalates stale tickets, and auto-closes old review tickets. Every 15 minutes.',
  },

  // ─── Executive Department ──────────────────────────────────────────────────
  {
    agent_name: 'Organization_Health_Agent',
    agent_type: 'organization_health',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/organizationHealthAgent.ts',
    trigger_type: 'cron',
    schedule: '0 * * * *',
    category: 'executive',
    description: 'Monitors overall AI organization health: department status, agent fleet performance, cross-department coordination issues. Hourly.',
  },
  {
    agent_name: 'Executive_Briefing_Agent',
    agent_type: 'executive_briefing',
    module: 'intelligence',
    source_file: 'backend/src/services/executiveBriefingService.ts',
    trigger_type: 'cron',
    schedule: '0 7 * * *',
    category: 'executive',
    description: 'Generates and delivers daily executive briefing with leads, pipeline, revenue, campaign performance, and system health. Daily at 7am.',
  },
  {
    agent_name: 'AutonomousEngine',
    agent_type: 'autonomous_engine',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/autonomy/autonomousEngine.ts',
    trigger_type: 'cron',
    schedule: '5,15,25,35,45,55 * * * *',
    category: 'executive',
    description: 'COO autonomous operations loop. Discovers problems, plans actions, estimates impact, evaluates risk, and executes approved changes. Every 10 min.',
  },
  {
    agent_name: 'AICOOStrategicCycle',
    agent_type: 'strategic_cycle',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/strategy/aiCOO.ts',
    trigger_type: 'cron',
    schedule: '0,30 * * * *',
    category: 'executive',
    description: 'AI COO strategic planning cycle. Revenue optimization, cost reduction, growth experiments, resource allocation, and governance review. Every 30 min.',
  },
  {
    agent_name: 'MetaAgentLoop',
    agent_type: 'meta_agent_loop',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/meta/metaAgentLoop.ts',
    trigger_type: 'cron',
    schedule: '2 * * * *',
    category: 'executive',
    description: 'Meta-agent oversight loop. Analyzes agent architecture, optimizes prompts, tracks performance, and runs experiments to improve the fleet. Hourly.',
  },

  // ─── Strategy Department ───────────────────────────────────────────────────
  {
    agent_name: 'Product_Strategy_Agent',
    agent_type: 'product_strategy',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/productStrategyAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'strategic',
    description: 'Analyzes product metrics, competitive positioning, and feature prioritization to recommend strategic product moves.',
  },
  {
    agent_name: 'Human_Learning_Strategy_Agent',
    agent_type: 'human_learning_strategy',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/humanLearningStrategyAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'strategic',
    description: 'Designs learning pathways, pedagogy strategies, and skill progression models for enterprise AI education.',
  },
  {
    agent_name: 'Program_Evolution_Agent',
    agent_type: 'program_evolution',
    module: 'intelligence',
    source_file: 'backend/src/intelligence/agents/programEvolutionAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'strategic',
    description: 'Evolves program offerings based on market signals, student outcomes, and industry trend analysis.',
  },

  // ─── Marketing Department ──────────────────────────────────────────────────
  {
    agent_name: 'Content_Marketing_Agent',
    agent_type: 'content_marketing',
    module: 'marketing',
    source_file: 'backend/src/services/agents/contentMarketingAgent.ts',
    trigger_type: 'cron',
    schedule: '0 8 * * *',
    category: 'outbound',
    description: 'Generates content ideas, drafts outreach copy, and optimizes marketing campaigns based on engagement data. Daily at 8am.',
  },

  // ─── Admissions Extensions ─────────────────────────────────────────────────
  {
    agent_name: 'Enterprise_Opportunity_Agent',
    agent_type: 'enterprise_opportunity',
    module: 'admissionsIntelligence',
    source_file: 'backend/src/services/agents/admissions/enterpriseOpportunityAgent.ts',
    trigger_type: 'event_driven',
    schedule: '',
    category: 'admissions',
    description: 'Detects enterprise buying signals from visitor patterns and conversation data, flags corporate enrollment opportunities.',
  },

  // ─── Alumni Department ─────────────────────────────────────────────────────
  {
    agent_name: 'Alumni_Outreach_Agent',
    agent_type: 'alumni_outreach',
    module: 'alumni',
    source_file: 'backend/src/services/agents/alumni/alumniOutreachAgent.ts',
    trigger_type: 'cron',
    schedule: '0 9 * * 1',
    category: 'alumni',
    description: 'Sends personalized check-ins to program alumni with career resources and community updates. Weekly on Monday.',
  },
  {
    agent_name: 'Alumni_Reengagement_Agent',
    agent_type: 'alumni_reengagement',
    module: 'alumni',
    source_file: 'backend/src/services/agents/alumni/alumniReengagementAgent.ts',
    trigger_type: 'cron',
    schedule: '0 10 * * 3',
    category: 'alumni',
    description: 'Identifies disengaged alumni and creates reengagement campaigns with advanced courses and mentorship opportunities. Weekly on Wednesday.',
  },
  {
    agent_name: 'Alumni_Referral_Agent',
    agent_type: 'alumni_referral',
    module: 'alumni',
    source_file: 'backend/src/services/agents/alumni/alumniReferralAgent.ts',
    trigger_type: 'event_driven',
    schedule: '',
    category: 'alumni',
    description: 'Tracks alumni referral patterns and incentivizes high-performing referrers with recognition and rewards.',
  },

  // ─── Partnerships Department ───────────────────────────────────────────────
  {
    agent_name: 'Enterprise_Partnership_Agent',
    agent_type: 'enterprise_partnership',
    module: 'partnerships',
    source_file: 'backend/src/services/agents/partnerships/enterprisePartnershipAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'partnerships',
    description: 'Manages enterprise partnership lifecycle: proposal generation, negotiation tracking, and contract management.',
  },
  {
    agent_name: 'Corporate_Training_Agent',
    agent_type: 'corporate_training',
    module: 'partnerships',
    source_file: 'backend/src/services/agents/partnerships/corporateTrainingAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'partnerships',
    description: 'Designs and manages corporate training programs: custom curricula, cohort scheduling, and enterprise reporting.',
  },
  {
    agent_name: 'Employer_Relationship_Agent',
    agent_type: 'employer_relationship',
    module: 'partnerships',
    source_file: 'backend/src/services/agents/partnerships/employerRelationshipAgent.ts',
    trigger_type: 'cron',
    schedule: '0 9 * * 5',
    category: 'partnerships',
    description: 'Nurtures employer relationships for hiring pipeline: job placement tracking, employer satisfaction, and partnership health. Weekly on Friday.',
  },

  // ─── Platform Extensions ───────────────────────────────────────────────────
  {
    agent_name: 'UX_Optimization_Agent',
    agent_type: 'ux_optimization',
    module: 'platform',
    source_file: 'backend/src/services/agents/platform/uxOptimizationAgent.ts',
    trigger_type: 'cron',
    schedule: '0 3 * * *',
    category: 'website_intelligence',
    description: 'Analyzes user interaction patterns to identify UX friction points, proposes improvements, and tracks conversion impact. Daily at 3am.',
  },
  {
    agent_name: 'Deployment_Agent',
    agent_type: 'deployment',
    module: 'platform',
    source_file: 'backend/src/services/agents/platform/deploymentAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'operations',
    description: 'Manages deployment workflows: pre-deploy checks, staged rollouts, health verification, and rollback triggers.',
  },
  {
    agent_name: 'Performance_Monitoring_Agent',
    agent_type: 'performance_monitoring',
    module: 'platform',
    source_file: 'backend/src/services/agents/platform/performanceMonitoringAgent.ts',
    trigger_type: 'cron',
    schedule: '*/15 * * * *',
    category: 'operations',
    description: 'Monitors API response times, database query performance, and resource utilization. Emits alerts when thresholds exceeded. Every 15 min.',
  },

  // ─── Intelligence Extensions ───────────────────────────────────────────────
  {
    agent_name: 'Data_Intelligence_Agent',
    agent_type: 'data_intelligence',
    module: 'intelligence',
    source_file: 'backend/src/services/agents/intelligence/dataIntelligenceAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'ai_ops',
    description: 'Aggregates cross-system data into actionable intelligence reports: enrollment trends, revenue patterns, lead scoring accuracy. Every 6 hours.',
  },
  {
    agent_name: 'Trend_Detection_Agent',
    agent_type: 'trend_detection',
    module: 'intelligence',
    source_file: 'backend/src/services/agents/intelligence/trendDetectionAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */4 * * *',
    category: 'behavioral',
    description: 'Detects emerging trends in visitor behavior, market signals, and enrollment patterns. Emits opportunity/warning alerts. Every 4 hours.',
  },
  {
    agent_name: 'Analytics_Agent',
    agent_type: 'analytics',
    module: 'intelligence',
    source_file: 'backend/src/services/agents/intelligence/analyticsAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'ai_ops',
    description: 'On-demand analytics: generates custom reports, answers data questions, and produces visualization-ready datasets.',
  },
  {
    agent_name: 'Opportunity_Detection_Agent',
    agent_type: 'opportunity_detection',
    module: 'intelligence',
    source_file: 'backend/src/services/agents/intelligence/opportunityDetectionAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */2 * * *',
    category: 'behavioral',
    description: 'Scans leads, visitors, and market data to surface revenue opportunities and high-potential prospects. Every 2 hours.',
  },

  // ─── Governance Department ─────────────────────────────────────────────────
  {
    agent_name: 'Policy_Agent',
    agent_type: 'policy',
    module: 'governance',
    source_file: 'backend/src/services/agents/governance/policyAgent.ts',
    trigger_type: 'cron',
    schedule: '0 2 * * *',
    category: 'governance_ops',
    description: 'Audits system operations against governance policies: data retention, AI autonomy limits, compliance requirements. Daily at 2am.',
  },
  {
    agent_name: 'Risk_Agent',
    agent_type: 'risk',
    module: 'governance',
    source_file: 'backend/src/services/agents/governance/riskAgent.ts',
    trigger_type: 'cron',
    schedule: '0 * * * *',
    category: 'governance_ops',
    description: 'Evaluates operational risk: agent error trends, data quality issues, security posture, and resource contention. Hourly.',
  },
  {
    agent_name: 'Approval_Agent',
    agent_type: 'approval',
    module: 'governance',
    source_file: 'backend/src/services/agents/governance/approvalAgent.ts',
    trigger_type: 'event_driven',
    schedule: '',
    category: 'governance_ops',
    description: 'Gates high-risk agent actions: reviews confidence scores, enforces approval workflows, and logs authorization decisions.',
  },

  // --- OpenClaw Autonomous Outreach Network ---
  {
    agent_name: 'OpenclawSupervisorAgent',
    agent_type: 'openclaw_supervisor',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawSupervisorAgent.ts',
    trigger_type: 'cron',
    schedule: '*/2 * * * *',
    category: 'openclaw',
    description: 'Task queue management, prioritization, concurrency enforcement, and stuck-task detection for the OpenClaw outreach network.',
    config: {
      max_concurrent_tasks: 3,
      stuck_task_threshold_ms: 600000,
      platform_rate_limits: {
        reddit: { max_posts_per_hour: 3, min_delay_ms: 120000, daily_cap: 15 },
        linkedin: { max_posts_per_hour: 2, min_delay_ms: 180000, daily_cap: 10 },
        hackernews: { max_posts_per_hour: 2, min_delay_ms: 300000, daily_cap: 8 },
        quora: { max_posts_per_hour: 3, min_delay_ms: 120000, daily_cap: 12 },
        devto: { max_posts_per_hour: 2, min_delay_ms: 180000, daily_cap: 10 },
        medium: { max_posts_per_hour: 1, min_delay_ms: 300000, daily_cap: 5 },
      },
    },
  },
  {
    agent_name: 'OpenclawMarketSignalAgent',
    agent_type: 'openclaw_research',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawMarketSignalAgent.ts',
    trigger_type: 'cron',
    schedule: '*/30 * * * *',
    category: 'openclaw',
    description: 'Scans Reddit, LinkedIn, HackerNews, Quora, Dev.to, and Medium for AI-related conversations matching target keywords.',
    config: {
      keywords: ['AI training', 'enterprise AI', 'AI leadership', 'AI upskilling', 'AI transformation', 'GenAI workforce', 'AI bootcamp'],
      platforms: ['reddit', 'hackernews', 'devto'],
      max_signals_per_scan: 50,
      require_approval: true,
    },
  },
  {
    agent_name: 'OpenclawConversationDetectionAgent',
    agent_type: 'openclaw_detection',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawConversationDetectionAgent.ts',
    trigger_type: 'cron',
    schedule: '5,35 * * * *',
    category: 'openclaw',
    description: 'Scores discovered signals for relevance, engagement potential, and risk. Queues high-scoring signals for content generation.',
    config: {
      relevance_threshold: 0.6,
      engagement_threshold: 0.4,
      risk_threshold: 0.7,
      max_queue_per_run: 20,
    },
  },
  {
    agent_name: 'OpenclawContentResponseAgent',
    agent_type: 'openclaw_content',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawContentResponseAgent.ts',
    trigger_type: 'cron',
    schedule: '10,40 * * * *',
    category: 'openclaw',
    description: 'Generates educational, platform-appropriate responses via LLM for queued signals. Creates draft responses pending approval.',
    config: {
      default_tone: 'educational',
      max_response_length: 1500,
      require_approval: true,
      utm_campaign: 'openclaw',
    },
  },
  {
    agent_name: 'OpenclawQualityGateAgent',
    agent_type: 'openclaw_quality_gate',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawQualityGateAgent.ts',
    trigger_type: 'cron',
    schedule: '5,20,35,50 * * * *',
    category: 'openclaw',
    description: 'Quality gate safety net for all automated platforms. Picks up rate-limited drafts, re-evaluates quality, and approves or rejects. Covers all API_POSTING platforms by default.',
    config: {
      max_reviews_per_run: 20,
    },
  },
  {
    agent_name: 'OpenclawBrowserWorkerAgent',
    agent_type: 'openclaw_browser',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawBrowserWorkerAgent.ts',
    trigger_type: 'cron',
    schedule: '15,45 * * * *',
    category: 'openclaw',
    description: 'Manages Playwright browser sessions to post approved responses. Handles authentication, screenshots, and session health.',
    config: {
      min_delay_ms: 2000,
      max_delay_ms: 8000,
      screenshot_on_post: true,
      headless: true,
    },
  },
  {
    agent_name: 'OpenclawLearningOptimizationAgent',
    agent_type: 'openclaw_learning',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawLearningOptimizationAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */4 * * *',
    category: 'openclaw',
    description: 'Analyzes engagement metrics by tone, timing, and topic. Creates learning entries and auto-optimizes strategy when confidence >= 0.7.',
    config: {
      min_sample_size: 10,
      confidence_threshold: 0.7,
      auto_apply_learnings: false,
    },
  },
  {
    agent_name: 'OpenclawInfraMonitorAgent',
    agent_type: 'openclaw_infra_monitor',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawInfraMonitorAgent.ts',
    trigger_type: 'cron',
    schedule: '*/5 * * * *',
    category: 'openclaw',
    description: 'Monitors browser session health. Detects captchas, crashes, and rate limits. Self-heals sessions and creates tickets for persistent failures.',
    config: {
      health_threshold: 0.3,
      max_consecutive_errors: 5,
      auto_restart_sessions: true,
    },
  },
  {
    agent_name: 'OpenclawTechResearchAgent',
    agent_type: 'openclaw_tech_research',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawTechResearchAgent.ts',
    trigger_type: 'cron',
    schedule: '0 6 * * *',
    category: 'openclaw',
    description: 'Daily scan of Playwright releases, anti-bot detection changes, and platform API updates. Logs findings as tech_update learnings.',
  },
  {
    agent_name: 'OpenclawAuthorityContentAgent',
    agent_type: 'openclaw_authority_content',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawAuthorityContentAgent.ts',
    trigger_type: 'cron',
    schedule: '0 8 * * *',
    category: 'openclaw',
    description: 'Daily authority content generator. Synthesizes recent signals into LinkedIn thought-leadership drafts. Groups signals by topic, uses best-performing tones from learnings.',
    config: {
      max_posts_per_run: 2,
      signal_window_hours: 48,
      base_url: 'https://enterprise.colaberry.ai',
    },
  },
  {
    agent_name: 'OpenclawEngagementMonitorAgent',
    agent_type: 'openclaw_engagement_monitor',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawEngagementMonitorAgent.ts',
    trigger_type: 'cron',
    schedule: '0,30 * * * *',
    category: 'openclaw',
    description: 'Scans posted responses and authority content for new engagement (comments/replies) via Dev.to, Hashnode, and Discourse APIs. Scores intent and detects role seniority.',
    config: {
      max_items_per_run: 20,
    },
  },
  {
    agent_name: 'OpenclawResponseOrchestratorAgent',
    agent_type: 'openclaw_response_orchestrator',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawResponseOrchestratorAgent.ts',
    trigger_type: 'cron',
    schedule: '10,25,40,55 * * * *',
    category: 'openclaw',
    description: 'Generates conversation follow-up drafts for new high-intent engagement events. Builds conversation chains and creates ResponseQueue entries with 48h expiry.',
    config: {
      min_intent_score: 0.3,
      max_per_run: 5,
      expiry_hours: 48,
    },
  },
  {
    agent_name: 'OpenclawFollowUpAgent',
    agent_type: 'openclaw_follow_up',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawFollowUpAgent.ts',
    trigger_type: 'cron',
    schedule: '0 10 * * *',
    category: 'openclaw',
    description: 'Daily follow-up agent for high-intent conversations that went silent after 48h+. Generates subtle follow-ups (max 3/day) and expires stale ResponseQueue drafts.',
    config: {
      min_intent_score: 0.6,
      max_follow_ups_per_run: 3,
      stale_hours: 48,
    },
  },
  {
    agent_name: 'OpenclawLinkedInFlowAgent',
    agent_type: 'openclaw_linkedin_flow',
    module: 'openclaw',
    source_file: 'backend/src/services/agents/openclaw/openclawLinkedInFlowAgent.ts',
    trigger_type: 'cron',
    schedule: '0 9,15 * * 1-5',
    category: 'openclaw',
    description: 'Generates LinkedIn action suggestions: comments on signals, connection requests for high-intent engagers, DM follow-ups. All actions human-in-the-loop — NEVER auto-executes.',
    config: {
      max_comments: 5,
      max_connections: 3,
      max_dms: 2,
    },
  },

  // --- Reporting Department agents ---
  {
    agent_name: 'KnowledgeGraphBuilderAgent',
    agent_type: 'knowledge_graph_builder',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/knowledgeGraphBuilderAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */2 * * *',
    category: 'reporting',
    description: 'Scans all system entities (campaigns, leads, agents, students, cohorts, curriculum) and builds/updates the Cory Knowledge Graph with nodes and relationship edges. Runs every 2 hours.',
  },
  {
    agent_name: 'ReportingIntelligenceAgent',
    agent_type: 'reporting_intelligence',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/reportingIntelligenceAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */4 * * *',
    category: 'reporting',
    description: 'Orchestrator for the Reporting Department. Scans system data every 4 hours, prioritizes analytics tasks, assigns reporting sub-agents, and publishes insights to Intelligence OS.',
  },
  {
    agent_name: 'InsightDiscoveryAgent',
    agent_type: 'insight_discovery',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/insightDiscoveryAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'reporting',
    description: 'Detects patterns and anomalies across campaigns, student behavior, conversions, agent performance, and curriculum engagement. Scores each insight by confidence, impact, urgency, and data strength.',
  },
  {
    agent_name: 'VisualizationAgent',
    agent_type: 'visualization_generation',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/visualizationAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'reporting',
    description: 'Transforms insights into visualization specs (charts, funnels, heatmaps, timelines, trend graphs, comparisons, entity maps) compatible with Intelligence OS dashboards.',
  },
  {
    agent_name: 'NarrativeAgent',
    agent_type: 'narrative_generation',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/narrativeAgent.ts',
    trigger_type: 'on_demand',
    schedule: '',
    category: 'reporting',
    description: 'Converts data insights into human-readable explanations with likely causes and actionable recommendations. Powers Cory explain, research, and recommend modes.',
  },
  {
    agent_name: 'TrendAnalysisAgent',
    agent_type: 'trend_analysis',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/trendAnalysisAgent.ts',
    trigger_type: 'cron',
    schedule: '0 3 * * *',
    category: 'reporting',
    description: 'Identifies long-term patterns across 7-day, 30-day, and 90-day windows. Tracks campaign performance trends, student learning velocity, curriculum improvement impact, conversion trends, and revenue patterns.',
  },
  {
    agent_name: 'MarketingReportingAgent',
    agent_type: 'department_reporter',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/departmentReporterAgent.ts',
    trigger_type: 'cron',
    schedule: '0 5 * * *',
    category: 'reporting',
    description: 'Analyzes Marketing department metrics and generates KPI snapshots. Tracks campaign ROI, open/reply rates, cost per lead, and funnel velocity.',
    config: { department: 'Marketing' },
  },
  {
    agent_name: 'AdmissionsReportingAgent',
    agent_type: 'department_reporter',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/departmentReporterAgent.ts',
    trigger_type: 'cron',
    schedule: '0 5 * * *',
    category: 'reporting',
    description: 'Analyzes Admissions department metrics and generates KPI snapshots. Tracks conversion rate, appointment show rate, pipeline velocity, and average deal cycle.',
    config: { department: 'Admissions' },
  },
  {
    agent_name: 'EducationReportingAgent',
    agent_type: 'department_reporter',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/departmentReporterAgent.ts',
    trigger_type: 'cron',
    schedule: '0 5 * * *',
    category: 'reporting',
    description: 'Analyzes Education department metrics and generates KPI snapshots. Tracks completion rates, assignment scores, session attendance, and curriculum coverage.',
    config: { department: 'Education' },
  },
  {
    agent_name: 'StudentSuccessReportingAgent',
    agent_type: 'department_reporter',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/departmentReporterAgent.ts',
    trigger_type: 'cron',
    schedule: '0 5 * * *',
    category: 'reporting',
    description: 'Analyzes Student Success department metrics and generates KPI snapshots. Tracks at-risk count, engagement score, satisfaction proxy, and retention rate.',
    config: { department: 'Student_Success' },
  },
  {
    agent_name: 'PlatformReportingAgent',
    agent_type: 'department_reporter',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/departmentReporterAgent.ts',
    trigger_type: 'cron',
    schedule: '0 5 * * *',
    category: 'reporting',
    description: 'Analyzes Platform department metrics and generates KPI snapshots. Tracks uptime, error rate, page load times, and agent fleet health.',
    config: { department: 'Platform' },
  },
  {
    agent_name: 'AlumniReportingAgent',
    agent_type: 'department_reporter',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/departmentReporterAgent.ts',
    trigger_type: 'cron',
    schedule: '0 5 * * *',
    category: 'reporting',
    description: 'Analyzes Alumni department metrics and generates KPI snapshots. Tracks reengagement rate, referral count, and community activity.',
    config: { department: 'Alumni' },
  },
  {
    agent_name: 'PartnershipsReportingAgent',
    agent_type: 'department_reporter',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/departmentReporterAgent.ts',
    trigger_type: 'cron',
    schedule: '0 5 * * *',
    category: 'reporting',
    description: 'Analyzes Partnerships department metrics and generates KPI snapshots. Tracks active partnerships, partner pipeline value, and training utilization.',
    config: { department: 'Partnerships' },
  },
  {
    agent_name: 'ExecutiveBriefingReportingAgent',
    agent_type: 'executive_briefing_reporting',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/executiveBriefingReportingAgent.ts',
    trigger_type: 'cron',
    schedule: '0 7 * * *',
    category: 'reporting',
    description: 'Generates daily executive summaries including new leads, admissions conversations, enrollments, revenue, campaign performance, system health, and top insights. Weekly strategic briefings on Mondays.',
  },
  {
    agent_name: 'ExperimentRecommendationAgent',
    agent_type: 'experiment_recommendation',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/experimentRecommendationAgent.ts',
    trigger_type: 'cron',
    schedule: '0 8 * * 1',
    category: 'reporting',
    description: 'Weekly agent that proposes experiments when insights indicate improvement potential. Creates experiment proposals and auto-generates tickets for testing new messaging, lesson structures, or admissions scripts.',
  },
  {
    agent_name: 'RevenueOpportunityAgent',
    agent_type: 'revenue_opportunity_detection',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/revenueOpportunityAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */8 * * *',
    category: 'reporting',
    description: 'Detects potential revenue opportunities from alumni at large companies, high-intent leads, and enterprise training signals. Estimates deal value and recommends outreach strategy.',
  },
  {
    agent_name: 'AgentPerformanceAnalyticsAgent',
    agent_type: 'agent_performance_analytics',
    module: 'reporting',
    source_file: 'backend/src/services/agents/reporting/agentPerformanceAnalyticsAgent.ts',
    trigger_type: 'cron',
    schedule: '0 4 * * *',
    category: 'reporting',
    description: 'Analyzes performance of all agents across the system. Tracks tickets completed, impact on KPIs, system improvements, and campaign performance impact. Generates agent ranking insights.',
  },

  // --- Department Strategy Architect agents (16) ---
  {
    agent_name: 'ExecutiveStrategyArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Executive Office. Evaluates organizational health, identifies cross-department alignment opportunities, and generates executive-level initiatives.',
    config: { department_slug: 'executive', agent_name: 'ExecutiveStrategyArchitect' },
  },
  {
    agent_name: 'GovernanceStrategyArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '2 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Governance & Compliance. Monitors compliance posture, identifies risk patterns, and ensures policy adherence across departments.',
    config: { department_slug: 'governance', agent_name: 'GovernanceStrategyArchitect' },
  },
  {
    agent_name: 'StrategyFuturesArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '4 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Strategy & Analytics. Drives data-driven planning, forecasting accuracy, and strategic initiative pipeline.',
    config: { department_slug: 'strategy', agent_name: 'StrategyFuturesArchitect' },
  },
  {
    agent_name: 'FinanceIntelligenceArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '6 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Finance. Optimizes cost structures, revenue forecasting accuracy, and scholarship allocation efficiency.',
    config: { department_slug: 'finance', agent_name: 'FinanceIntelligenceArchitect' },
  },
  {
    agent_name: 'OperationsOptimizationArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '8 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Operations. Drives workflow optimization, quality assurance improvements, and process automation.',
    config: { department_slug: 'operations', agent_name: 'OperationsOptimizationArchitect' },
  },
  {
    agent_name: 'OrchestrationEcosystemArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '10 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Orchestration. Coordinates agent fleet performance, decision simulation, and system-wide optimization.',
    config: { department_slug: 'orchestration', agent_name: 'OrchestrationEcosystemArchitect' },
  },
  {
    agent_name: 'InsightArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '12 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Intelligence & AI Ops. Identifies anomaly patterns, generates strategic insights, and improves autonomous operations.',
    config: { department_slug: 'intelligence', agent_name: 'InsightArchitect' },
  },
  {
    agent_name: 'PartnershipExpansionArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '14 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Partnerships. Identifies expansion opportunities, strengthens corporate relationships, and develops institutional alliances.',
    config: { department_slug: 'partnerships', agent_name: 'PartnershipExpansionArchitect' },
  },
  {
    agent_name: 'GrowthExperimentArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '16 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Growth. Designs growth experiments, scans for expansion opportunities, and drives partnership development.',
    config: { department_slug: 'growth', agent_name: 'GrowthExperimentArchitect' },
  },
  {
    agent_name: 'MarketingAutomationArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '18 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Marketing. Optimizes lead generation, content strategy, campaign performance, and brand positioning.',
    config: { department_slug: 'marketing', agent_name: 'MarketingAutomationArchitect' },
  },
  {
    agent_name: 'AdmissionsConversionArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '20 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Admissions. Improves enrollment pipeline, student recruitment efficiency, and conversion optimization.',
    config: { department_slug: 'admissions', agent_name: 'AdmissionsConversionArchitect' },
  },
  {
    agent_name: 'InfrastructureEvolutionArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '22 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Infrastructure. Monitors system health, security posture, AI model performance, and reliability improvements.',
    config: { department_slug: 'infrastructure', agent_name: 'InfrastructureEvolutionArchitect' },
  },
  {
    agent_name: 'PlatformInnovationArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '24 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Platform. Drives UX optimization, deployment improvements, and performance monitoring enhancements.',
    config: { department_slug: 'platform', agent_name: 'PlatformInnovationArchitect' },
  },
  {
    agent_name: 'LearningInnovationArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '26 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Education. Innovates curriculum design, content generation methods, and learning outcome measurement.',
    config: { department_slug: 'education', agent_name: 'LearningInnovationArchitect' },
  },
  {
    agent_name: 'StudentSuccessArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '28 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Student Success. Improves retention, mentoring programs, learning outcomes, and student experience.',
    config: { department_slug: 'student_success', agent_name: 'StudentSuccessArchitect' },
  },
  {
    agent_name: 'AlumniNetworkArchitect',
    agent_type: 'dept_strategy_architect',
    module: 'strategyArchitectAgent',
    source_file: 'backend/src/services/agents/strategy/strategyArchitectAgent.ts',
    trigger_type: 'cron',
    schedule: '30 */6 * * *',
    category: 'dept_strategy',
    description: 'Strategic planning agent for Alumni Relations. Strengthens post-graduation engagement, referral programs, and community building.',
    config: { department_slug: 'alumni', agent_name: 'AlumniNetworkArchitect' },
  },

  // --- Security Operations Department (8 agents) ---
  {
    agent_name: 'SecurityDirectorAgent',
    agent_type: 'security_director',
    module: 'security',
    source_file: 'backend/src/services/agents/security/securityDirectorAgent.ts',
    trigger_type: 'cron',
    schedule: '*/10 * * * *',
    category: 'security_ops',
    description: 'Coordinator agent for Security Operations. Aggregates recent security events, checks open tickets, monitors subordinate agent health, and creates tickets for unaddressed critical threats.',
  },
  {
    agent_name: 'SecretDetectionAgent',
    agent_type: 'secret_detection',
    module: 'security',
    source_file: 'backend/src/services/agents/security/secretDetectionAgent.ts',
    trigger_type: 'cron',
    schedule: '0 */4 * * *',
    category: 'security_ops',
    description: 'Scans source files for leaked secrets: AWS keys, private keys, connection strings, JWT tokens, API keys, and platform-specific credentials. Every 4 hours.',
  },
  {
    agent_name: 'CodeSecurityAuditAgent',
    agent_type: 'code_security',
    module: 'security',
    source_file: 'backend/src/services/agents/security/codeSecurityAuditAgent.ts',
    trigger_type: 'cron',
    schedule: '0 3 * * *',
    category: 'security_ops',
    description: 'Static analysis for SQL injection, XSS, command injection, eval usage, and path traversal vulnerabilities in backend TypeScript files. Daily at 3 AM.',
  },
  {
    agent_name: 'DependencySecurityAgent',
    agent_type: 'dependency_security',
    module: 'security',
    source_file: 'backend/src/services/agents/security/dependencySecurityAgent.ts',
    trigger_type: 'cron',
    schedule: '0 4 * * *',
    category: 'security_ops',
    description: 'Runs npm audit on backend and frontend projects to detect vulnerable dependencies. Creates tickets for critical and high CVEs. Daily at 4 AM.',
  },
  {
    agent_name: 'RuntimeThreatMonitorAgent',
    agent_type: 'runtime_threat',
    module: 'security',
    source_file: 'backend/src/services/agents/security/runtimeThreatMonitorAgent.ts',
    trigger_type: 'cron',
    schedule: '*/5 * * * *',
    category: 'security_ops',
    description: 'Monitors runtime activity for scraping detection (high-volume visitors) and agent failure spikes. Every 5 minutes.',
  },
  {
    agent_name: 'AccessControlGuardianAgent',
    agent_type: 'access_control',
    module: 'security',
    source_file: 'backend/src/services/agents/security/accessControlGuardianAgent.ts',
    trigger_type: 'cron',
    schedule: '0 5 * * *',
    category: 'security_ops',
    description: 'Audits route definitions for missing authentication middleware. Checks admin routes for requireAdmin, mutation endpoints for auth guards. Daily at 5 AM.',
  },
  {
    agent_name: 'AISafetyMonitorAgent',
    agent_type: 'ai_safety',
    module: 'security',
    source_file: 'backend/src/services/agents/security/aiSafetyMonitorAgent.ts',
    trigger_type: 'cron',
    schedule: '2,7,12,17,22,27,32,37,42,47,52,57 * * * *',
    category: 'security_ops',
    description: 'Scans recent visitor chat messages for prompt injection attempts: system prompt overrides, role impersonation, jailbreaks, command probes. Every 5 minutes (offset).',
  },
  {
    agent_name: 'AgentBehaviorMonitorAgent',
    agent_type: 'agent_behavior',
    module: 'security',
    source_file: 'backend/src/services/agents/security/agentBehaviorMonitorAgent.ts',
    trigger_type: 'cron',
    schedule: '5,15,25,35,45,55 * * * *',
    category: 'security_ops',
    description: 'Monitors agent fleet for anomalies: stuck agents (running >15min), error spikes (>5/hr), and execution duration outliers (>3x average). Every 10 minutes.',
  },
  {
    agent_name: 'AdmissionsKnowledgeSyncAgent',
    agent_type: 'monitor',
    module: 'admissionsKnowledgeSyncAgent',
    source_file: 'backend/src/services/agents/admissions/admissionsKnowledgeSyncAgent.ts',
    trigger_type: 'cron',
    schedule: '0 3 * * *',
    category: 'admissions',
    description: 'Crawls public website pages daily and auto-updates Maya knowledge base entries when content changes. Detects stale entries and flags them for review.',
  },

  // --- Department Super Agents ---
  {
    agent_name: 'CampaignOpsSuperAgent',
    agent_type: 'super_agent',
    module: 'superAgents',
    source_file: 'backend/src/services/agents/departments/superAgents/campaignOpsSuperAgent.ts',
    trigger_type: 'cron',
    schedule: '3,33 * * * *',
    category: 'dept_super',
    description: 'Aggregates signals from CampaignHealthScanner, RepairAgent, QAAgent, SelfHealingAgent. Detects anomalies and produces department report for Campaign Operations.',
  },
  {
    agent_name: 'LeadIntelligenceSuperAgent',
    agent_type: 'super_agent',
    module: 'superAgents',
    source_file: 'backend/src/services/agents/departments/superAgents/leadIntelligenceSuperAgent.ts',
    trigger_type: 'cron',
    schedule: '5,35 * * * *',
    category: 'dept_super',
    description: 'Aggregates signals from lead scoring, enrichment, routing, and qualification agents. Produces department report for Lead Intelligence.',
  },
  {
    agent_name: 'ContentEngineSuperAgent',
    agent_type: 'super_agent',
    module: 'superAgents',
    source_file: 'backend/src/services/agents/departments/superAgents/contentEngineSuperAgent.ts',
    trigger_type: 'cron',
    schedule: '7,37 * * * *',
    category: 'dept_super',
    description: 'Aggregates signals from content optimization, copy variant, and subject line agents. Produces department report for Content Engine.',
  },
  {
    agent_name: 'AnalyticsEngineSuperAgent',
    agent_type: 'super_agent',
    module: 'superAgents',
    source_file: 'backend/src/services/agents/departments/superAgents/analyticsEngineSuperAgent.ts',
    trigger_type: 'cron',
    schedule: '9,39 * * * *',
    category: 'dept_super',
    description: 'Aggregates signals from KPI, cohort, funnel, and campaign analytics agents. Produces department report for Analytics Engine.',
  },
  {
    agent_name: 'SystemResilienceSuperAgent',
    agent_type: 'super_agent',
    module: 'superAgents',
    source_file: 'backend/src/services/agents/departments/superAgents/systemResilienceSuperAgent.ts',
    trigger_type: 'cron',
    schedule: '11,41 * * * *',
    category: 'dept_super',
    description: 'Aggregates signals from error recovery, system health, database optimizer, and cache manager agents. Produces department report for System Resilience.',
  },
  {
    agent_name: 'AdmissionsSuperAgent',
    agent_type: 'super_agent',
    module: 'superAgents',
    source_file: 'backend/src/services/agents/departments/superAgents/admissionsSuperAgent.ts',
    trigger_type: 'cron',
    schedule: '13,43 * * * *',
    category: 'dept_super',
    description: 'Aggregates signals from all admissions intelligence and operations agents. Produces department report for Admissions.',
  },
  {
    agent_name: 'PartnershipSuperAgent',
    agent_type: 'super_agent',
    module: 'superAgents',
    source_file: 'backend/src/services/agents/departments/superAgents/partnershipSuperAgent.ts',
    trigger_type: 'cron',
    schedule: '15,45 * * * *',
    category: 'dept_super',
    description: 'Aggregates signals from partner outreach and performance agents. Produces department report for Partnerships.',
  },
  {
    agent_name: 'FinanceSuperAgent',
    agent_type: 'super_agent',
    module: 'superAgents',
    source_file: 'backend/src/services/agents/departments/superAgents/financeSuperAgent.ts',
    trigger_type: 'cron',
    schedule: '17,47 * * * *',
    category: 'dept_super',
    description: 'Aggregates signals from budget, ROI, and cost optimization agents. Produces department report for Finance.',
  },
];

/**
 * Seed the full agent registry (129 agents). Idempotent — uses findOrCreate
 * and updates existing rows with registry metadata.
 */
export async function seedAgentRegistry(): Promise<void> {
  for (const entry of AGENT_REGISTRY) {
    const [agent, created] = await AiAgent.findOrCreate({
      where: { agent_name: entry.agent_name },
      defaults: entry,
    });

    if (!created) {
      // Update registry fields on existing agents (preserves status, config, run stats)
      await agent.update({
        agent_type: entry.agent_type,
        module: entry.module,
        source_file: entry.source_file,
        trigger_type: entry.trigger_type,
        schedule: entry.schedule,
        category: entry.category,
        description: entry.description,
        // Only set config if it wasn't customized (still empty)
        ...(Object.keys(agent.config || {}).length === 0 && entry.config ? { config: entry.config } : {}),
      });
    } else {
      console.log(`[AI Ops] Registered agent: ${entry.agent_name}`);
    }

    // Safety: Force-disable agents that bypass safety pipelines
    // ContentOptimizationAgent overwrites email content with fake lead name — CRITICAL safety issue
    if (entry.agent_name === 'ContentOptimizationAgent' && agent.enabled) {
      await agent.update({ enabled: false, status: 'paused' });
      console.warn(`[AI Ops] SAFETY: Disabled ${entry.agent_name} — must use suggestion-only mode`);
    }
  }

  // Assign agent_group to existing agents for super-agent aggregation
  await assignAgentGroups();
}

// ─── Agent Group Assignment ────────────────────────────────────────────────
// Maps agent names to their super-agent group. This is additive — does not
// remove agents or change any other field.

const AGENT_GROUP_MAP: Record<string, string[]> = {
  campaign_ops: [
    'CampaignHealthScanner', 'CampaignRepairAgent', 'CampaignQAAgent',
    'CampaignSelfHealingAgent', 'ContentOptimizationAgent', 'ConversationOptimizationAgent',
  ],
  lead_intelligence: [
    'ApolloLeadIntelligenceAgent', 'BehavioralSignalDetector', 'IntentScoreRecomputer',
    'BehavioralTriggerEvaluator', 'OpportunityScoreRecomputer', 'ICPInsightComputer',
  ],
  content_engine: [
    'ContentOptimizationAgent', 'ConversationOptimizationAgent',
  ],
  analytics_engine: [
    'InsightArchitect',
  ],
  system_resilience: [
    'OrchestrationHealthAgent', 'OrchestrationAutoRepairAgent', 'PromptMonitorAgent',
  ],
  admissions: [
    'AdmissionsVisitorIdentityAgent', 'AdmissionsVisitorActivityAgent',
    'AdmissionsConversationMemoryAgent', 'AdmissionsIntentDetectionAgent',
    'AdmissionsProactiveOutreachAgent', 'AdmissionsConversationContinuityAgent',
    'AdmissionsHighIntentLeadAgent', 'AdmissionsInsightsAgent', 'AdmissionsExecutiveUpdateAgent',
    'AdmissionsDocumentDeliveryAgent', 'AdmissionsEmailAgent', 'AdmissionsSMSAgent',
    'AdmissionsAppointmentAgent', 'AdmissionsSynthflowCallAgent', 'AdmissionsCallGovernanceAgent',
    'AdmissionsCallComplianceAgent', 'AdmissionsCallbackAgent', 'AdmissionsConversationTaskMonitor',
    'AdmissionsAssistantAgent', 'AdmissionsKnowledgeSyncAgent',
  ],
  partnership: [
    'PartnershipExpansionArchitect',
  ],
  finance: [
    'FinanceIntelligenceArchitect',
  ],
};

async function assignAgentGroups(): Promise<void> {
  for (const [group, agentNames] of Object.entries(AGENT_GROUP_MAP)) {
    for (const name of agentNames) {
      await AiAgent.update(
        { agent_group: group },
        { where: { agent_name: name, agent_group: { [Op.eq]: null as any } } },
      );
    }
  }
}
