/**
 * Project Scaffold Initialization Service
 *
 * Generates initial project structure and pushes to the participant's
 * GitHub repository after the system design contract is locked.
 */
import { ProjectSystemContract } from '../models';
import { getProjectByEnrollment } from './projectService';
import { getConnection, writeMultipleFilesToRepo } from './githubService';
import { generateClaudeMd, generateProjectState } from './claudeMdService';
import { getRequirementsStatus } from './requirementsMatchingService';

interface ScaffoldFile {
  path: string;
  content: string;
}

interface ScaffoldResult {
  filesGenerated: number;
  filesWritten: number;
  files: string[];
  errors: string[];
}

// ---------------------------------------------------------------------------
// 1. Generate scaffold file manifest
// ---------------------------------------------------------------------------

async function generateScaffoldFiles(enrollmentId: string): Promise<ScaffoldFile[]> {
  const project = await getProjectByEnrollment(enrollmentId);
  if (!project) throw new Error('No project found');

  const files: ScaffoldFile[] = [];

  // 1. CLAUDE.md — from claudeMdService
  const claudeMd = await generateClaudeMd(enrollmentId);
  files.push({ path: 'CLAUDE.md', content: claudeMd });

  // 2. PROJECT_STATE.json
  const projectState = await generateProjectState(enrollmentId);
  files.push({ path: 'PROJECT_STATE.json', content: projectState });

  // 3. README.md
  const readme = generateReadme(project);
  files.push({ path: 'README.md', content: readme });

  // 4. requirements/master.md — from compiled requirements
  const reqContent = await generateRequirementsMd(project.id);
  if (reqContent) {
    files.push({ path: 'requirements/master.md', content: reqContent });
  }

  // 5. Folder stubs from contract architecture
  const contractFolders = await getContractFolders(project.id);
  for (const folder of contractFolders) {
    files.push({ path: `${folder}/.gitkeep`, content: '' });
  }

  // 6. .gitignore
  files.push({ path: '.gitignore', content: generateGitignore() });

  return files;
}

// ---------------------------------------------------------------------------
// 2. Push scaffold to repo
// ---------------------------------------------------------------------------

export async function generateAndPushScaffold(enrollmentId: string): Promise<ScaffoldResult> {
  const connection = await getConnection(enrollmentId);
  if (!connection) throw new Error('No GitHub repository connected');
  if (!connection.access_token_encrypted) throw new Error('No GitHub access token — cannot write to repo');

  const files = await generateScaffoldFiles(enrollmentId);
  const result: ScaffoldResult = {
    filesGenerated: files.length,
    filesWritten: 0,
    files: files.map(f => f.path),
    errors: [],
  };

  const { filesWritten } = await writeMultipleFilesToRepo(
    enrollmentId,
    files,
    'Initialize project scaffold'
  );
  result.filesWritten = filesWritten;

  if (filesWritten < files.length) {
    result.errors.push(`${files.length - filesWritten} file(s) failed to write`);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function generateReadme(project: any): string {
  const lines = [
    `# ${project.organization_name || 'AI Project'}`,
    '',
    project.primary_business_problem
      ? `> ${project.primary_business_problem}`
      : '',
    '',
    '## Overview',
    '',
    `This project was initialized from the Colaberry Enterprise AI Leadership Accelerator.`,
    '',
    project.selected_use_case ? `**Use Case:** ${project.selected_use_case}` : '',
    project.automation_goal ? `**Goal:** ${project.automation_goal}` : '',
    '',
    '## Getting Started',
    '',
    '1. Read `CLAUDE.md` for full project context',
    '2. Review `requirements/master.md` for detailed requirements',
    '3. Check `PROJECT_STATE.json` for current progress',
    '',
    '## Project Structure',
    '',
    '```',
    '├── CLAUDE.md              # AI context file (auto-generated)',
    '├── PROJECT_STATE.json     # Machine-readable state',
    '├── requirements/',
    '│   └── master.md          # System requirements',
    '├── src/                   # Application source code',
    '├── tests/                 # Test files',
    '└── docs/                  # Documentation',
    '```',
    '',
    '---',
    '*Generated by Colaberry Enterprise AI Leadership Accelerator*',
  ].filter(Boolean);

  return lines.join('\n');
}

async function generateRequirementsMd(projectId: string): Promise<string | null> {
  try {
    const reqStatus = await getRequirementsStatus(projectId);
    if (!reqStatus.requirements || reqStatus.requirements.length === 0) return null;

    const lines = [
      '# System Requirements',
      '',
      `Total: ${reqStatus.requirements.length} requirements`,
      '',
    ];

    for (const req of reqStatus.requirements) {
      const status = req.status === 'verified' || req.status === 'matched'
        ? '✅' : req.status === 'partial' ? '🔄' : '⬜';
      lines.push(`${status} **${req.requirement_key}**: ${req.requirement_text}`);
      if (req.github_file_paths?.length) {
        lines.push(`  - Files: ${req.github_file_paths.join(', ')}`);
      }
      lines.push('');
    }

    return lines.join('\n');
  } catch {
    return null;
  }
}

async function getContractFolders(projectId: string): Promise<string[]> {
  const defaultFolders = ['src', 'tests', 'docs'];

  try {
    const contract = await ProjectSystemContract.findOne({
      where: { project_id: projectId },
      order: [['created_at', 'DESC']],
    });
    if (!contract || !(contract as any).contract_json) return defaultFolders;

    const data = (contract as any).contract_json;
    const folders = new Set<string>(defaultFolders);

    // Extract folder hints from contract structure
    if (data.components && Array.isArray(data.components)) {
      for (const comp of data.components) {
        if (comp.folder) folders.add(comp.folder);
      }
    }
    if (data.agents) folders.add('src/agents');
    if (data.services) folders.add('src/services');
    if (data.api_endpoints) folders.add('src/api');

    return Array.from(folders);
  } catch {
    return defaultFolders;
  }
}

function generateGitignore(): string {
  return [
    'node_modules/',
    '.env',
    '.env.local',
    'dist/',
    'build/',
    '*.log',
    '.DS_Store',
    '__pycache__/',
    '*.pyc',
    '.venv/',
    'venv/',
  ].join('\n');
}
