import { Router } from 'express';
import { auditMiddleware } from '../middlewares/auditMiddleware';
import authRoutes from './admin/authRoutes';
import cohortRoutes from './admin/cohortRoutes';
import leadRoutes from './admin/leadRoutes';
import campaignRoutes from './admin/campaignRoutes';
import insightRoutes from './admin/insightRoutes';
import settingsRoutes from './admin/settingsRoutes';
import acceleratorRoutes from './admin/acceleratorRoutes';
import orchestrationRoutes from './admin/orchestrationRoutes';
import aiOpsRoutes from './admin/aiOpsRoutes';
import intelligenceRoutes from './admin/intelligenceRoutes';
import campaignTestRoutes from './admin/campaignTestRoutes';
import campaignSimulationRoutes from './admin/campaignSimulationRoutes';
import marketingRoutes from './admin/marketingRoutes';
import governanceRoutes from './admin/governanceRoutes';
import campaignIntelligenceRoutes from './admin/campaignIntelligenceRoutes';
import alumniRoutes from './admin/alumniRoutes';
import autonomyRoutes from './admin/autonomyRoutes';
import coryRoutes from './admin/coryRoutes';
import departmentIntelligenceRoutes from './admin/departmentIntelligenceRoutes';
import websiteIntelligenceRoutes from './admin/websiteIntelligenceRoutes';
import admissionsRoutes from './admin/admissionsRoutes';
import ticketRoutes from './admin/ticketRoutes';
import previewRoutes from './admin/previewRoutes';
import alertRoutes from './admin/alertRoutes';
import openclawRoutes from './admin/openclawRoutes';
import reportingRoutes from './admin/reportingRoutes';
import governanceCenterRoutes from './admin/governanceCenterRoutes';
import executiveAwarenessRoutes from './admin/executiveAwarenessRoutes';
import strategicIntelligenceRoutes from './admin/strategicIntelligenceRoutes';
import securityRoutes from './admin/securityRoutes';
import deploymentRoutes from './admin/deploymentRoutes';
import schedulerControlRoutes from './admin/schedulerControlRoutes';
import agentGovernanceRoutes from './admin/agentGovernanceRoutes';
import projectOverviewRoutes from './admin/projectOverviewRoutes';
import testSetupRoutes from './admin/testSetupRoutes';
import productionCleanupRoutes from './admin/productionCleanupRoute';
import productionActivationRoutes from './admin/productionActivationRoute';
import campaignDiagnosticsRoutes from './admin/campaignDiagnosticsRoutes';
import visitorFlowRoutes from './admin/visitorFlowRoutes';
import marketingFunnelRoutes from './admin/marketingFunnelRoutes';
import artifactRelationshipRoutes from './admin/artifactRelationshipRoutes';
import dashboardRoutes from './admin/dashboardRoutes';
import communicationRoutes from './admin/communicationRoutes';
import businessProcessRoutes from './admin/businessProcessRoutes';

const router = Router();

router.use(auditMiddleware);
router.use(authRoutes);
router.use(cohortRoutes);
router.use(leadRoutes);
router.use(campaignRoutes);
router.use(insightRoutes);
router.use(settingsRoutes);
router.use(acceleratorRoutes);
router.use(orchestrationRoutes);
router.use(aiOpsRoutes);
router.use(intelligenceRoutes);
router.use(campaignTestRoutes);
router.use(campaignSimulationRoutes);
router.use(marketingRoutes);
router.use(governanceRoutes);
router.use(campaignIntelligenceRoutes);
router.use(alumniRoutes);
router.use(autonomyRoutes);
router.use(coryRoutes);
router.use(departmentIntelligenceRoutes);
router.use(websiteIntelligenceRoutes);
router.use(admissionsRoutes);
router.use(ticketRoutes);
router.use(previewRoutes);
router.use(alertRoutes);
router.use(openclawRoutes);
router.use(reportingRoutes);
router.use(governanceCenterRoutes);
router.use(executiveAwarenessRoutes);
router.use(strategicIntelligenceRoutes);
router.use(securityRoutes);
router.use(deploymentRoutes);
router.use(schedulerControlRoutes);
router.use(agentGovernanceRoutes);
router.use(projectOverviewRoutes);
router.use(testSetupRoutes);
router.use(productionCleanupRoutes);
router.use(productionActivationRoutes);
router.use(campaignDiagnosticsRoutes);
router.use(visitorFlowRoutes);
router.use(marketingFunnelRoutes);
router.use(artifactRelationshipRoutes);
router.use(dashboardRoutes);
router.use(communicationRoutes);
router.use(businessProcessRoutes);

export default router;
