/**
 * A concept is a shareable artifact generated by a model, which makes it the riskiest thing
 * this build produces: it goes in front of a customer, it can be forwarded, and nobody
 * reads the HTML before it ships.
 *
 * So the three checkable constraints from §21 are checked here rather than requested in the
 * prompt — "the prompt told it not to" has already been wrong repeatedly in this build.
 */

const mockChatJson = jest.fn();
jest.mock('../../runtime/runtimeAi', () => ({ chatJson: (...a: any[]) => mockChatJson(...a) }));

import {
  generateConcept,
  generateConcepts,
  buildConceptPrompt,
  contactLeakViolation,
  labelViolation,
  craftViolation,
  CONCEPT_LABEL,
  MIN_CSS_CHARS,
} from '../uiConceptGenerator';
import { buildDesignBrief } from '../designBrief';
import { parseUnderstanding } from '../projectUnderstanding';
import { projectBlueprint } from '../buildBlueprint';

const said = (dimension: string, value: string) => ({
  dimension,
  value,
  classification: 'FACT' as const,
  provenance: 'client_confirmed' as const,
});

const understanding = parseUnderstanding({
  title: 'Dispatcher Workflow Automation',
  proposed_surfaces: ['Reporting dashboard'],
  items: [
    said('actors', 'Ralph is the keeper of the spreadsheet and the project manager.'),
    said('current_workflow', 'A Power BI report is generated after running a SQL stored procedure.'),
    said('outputs', 'When a job is refused, reasons are noted in Slack.'),
  ],
});

const brief = buildDesignBrief(understanding, projectBlueprint(understanding));

/**
 * A fixture that clears the craft bar, because the bar is the point.
 *
 * The first version of this fixture had a single `font:14px sans-serif` rule and the craft
 * gate refused it — correctly. Lowering the threshold to accommodate a lazy fixture would
 * have quietly disabled the check this file exists to hold.
 */
const goodHtml =
  '<style>' +
  ':root{--fg:#1a1a1a;--muted:#6b6b6b;--surface:#ffffff;--bg:#faf9f7;--accent:#ba430e;--line:#e6e3df}' +
  'body{font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;background:var(--bg);color:var(--fg);margin:0}' +
  '.card{background:var(--surface);border:1px solid var(--line);border-radius:8px;padding:24px;margin:16px}' +
  '.title{font-size:24px;font-weight:600;letter-spacing:-0.01em;margin:0 0 8px}' +
  '.label{font-size:12px;text-transform:uppercase;letter-spacing:0.05em;color:var(--muted)}' +
  'table{border-collapse:collapse;width:100%}th{text-align:left;font-size:12px;color:var(--muted);padding:8px 12px}' +
  'td{padding:12px;border-top:1px solid var(--line);font-variant-numeric:tabular-nums}' +
  '.pill{display:inline-block;padding:2px 10px;border-radius:999px;font-size:12px;border:1px solid var(--line)}' +
  '</style>' +
  '<div class="card"><p class="label">Concept — illustrative data</p>' +
  '<h1 class="title">Dispatch Command Center</h1>' +
  '<p>Ralph · Power BI rebuild · refusal noted in Slack</p></div>';

const ok = (parsed: any) => ({ parsed, runtime_ms: 2400, cost_usd: 0.01 });

beforeEach(() => {
  jest.clearAllMocks();
  mockChatJson.mockResolvedValue(ok({ rationale: 'The screen Ralph keeps open.', html: goodHtml }));
});

describe('contact details must never reach a shareable artifact', () => {
  it('refuses a concept containing the email they typed into the form', () => {
    const html = goodHtml + '<p>ali@colaberry.com</p>';
    expect(contactLeakViolation(html, { email: 'ali@colaberry.com' })).toContain('email address');
  });

  it('catches a phone number even when it is formatted differently', () => {
    // "(682) 597-5784" and "+16825975784" are the same number; only one would ever be
    // caught by a literal search.
    const html = goodHtml + '<p>Call (682) 597-5784</p>';
    expect(contactLeakViolation(html, { phone: '+16825975784' })).toContain('phone number');
  });

  it('allows a first name — that is domain vocabulary, not contact data', () => {
    // The whole point of §20 is a screen that names the person who keeps the spreadsheet.
    expect(contactLeakViolation(goodHtml, { email: 'ali@colaberry.com', phone: '+16825975784' })).toBeNull();
  });

  it('does nothing when there is no contact data to leak', () => {
    expect(contactLeakViolation(goodHtml, {})).toBeNull();
  });

  it('does not false-positive on a short or empty phone', () => {
    expect(contactLeakViolation('<p>ext 12</p>', { phone: '12' })).toBeNull();
  });
});

describe('a concept must know it is a concept', () => {
  it('refuses html that never says so', () => {
    expect(labelViolation('<h1>Dispatch Command Center</h1>')).toContain('label itself');
  });

  it('accepts it in any casing', () => {
    expect(labelViolation('<p>CONCEPT — illustrative</p>')).toBeNull();
    expect(CONCEPT_LABEL).toBe('Concept');
  });
});

describe('generateConcept', () => {
  it('returns a checked concept on the happy path', async () => {
    const { concept, rejected } = await generateConcept({ brief, conceptKey: 'command_center' });

    expect(rejected).toBeUndefined();
    expect(concept).toMatchObject({ key: 'command_center', title: 'Command Center', recommended: true });
    expect(concept?.rationale).toBe('The screen Ralph keeps open.');
  });

  it('falls back to the variant intent when the model gives no rationale', async () => {
    mockChatJson.mockResolvedValue(ok({ html: goodHtml }));
    const { concept } = await generateConcept({ brief, conceptKey: 'operational' });
    expect(concept?.rationale).toContain('all day');
  });

  it('rejects a renamed template', async () => {
    mockChatJson.mockResolvedValue(
      ok({ html: '<p>Concept</p><h1>Operations Dashboard</h1><nav>Overview · Users · Settings</nav>' }),
    );

    const { concept, rejected } = await generateConcept({ brief, conceptKey: 'operational' });

    expect(concept).toBeUndefined();
    expect(rejected?.reason).toContain('generic template');
  });

  it('rejects an unlabelled concept even when it is otherwise good', async () => {
    mockChatJson.mockResolvedValue(ok({ html: '<h1>Ralph · Power BI rebuild</h1>' }));

    const { rejected } = await generateConcept({ brief, conceptKey: 'operational' });
    expect(rejected?.reason).toContain('label itself');
  });

  it('rejects a concept that leaked contact details', async () => {
    mockChatJson.mockResolvedValue(ok({ html: goodHtml + '<p>ali@colaberry.com</p>' }));

    const { rejected } = await generateConcept({
      brief,
      conceptKey: 'operational',
      contact: { email: 'ali@colaberry.com' },
    });

    expect(rejected?.reason).toContain('email address');
  });

  it('rejects an empty response rather than shipping a blank screen', async () => {
    mockChatJson.mockResolvedValue(ok({ rationale: 'hi' }));
    const { rejected } = await generateConcept({ brief, conceptKey: 'operational' });
    expect(rejected?.reason).toContain('no html');
  });
});

describe('generateConcepts', () => {
  it('generates each variant in a SEPARATE call, so they do not converge', async () => {
    const result = await generateConcepts({ brief });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.concepts).toHaveLength(3);
    // Three concepts in one response makes the model write a theme and vary the header,
    // which is the §20 failure arriving from a different direction.
    expect(mockChatJson).toHaveBeenCalledTimes(3);
  });

  it('sums cost and runtime across the calls', async () => {
    const result = await generateConcepts({ brief });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.cost_usd).toBeCloseTo(0.03);
  });

  it('keeps the good concepts when one is refused', async () => {
    mockChatJson
      .mockResolvedValueOnce(ok({ html: '<h1>Overview · Users · Settings</h1><p>Concept</p>' }))
      .mockResolvedValue(ok({ html: goodHtml }));

    const result = await generateConcepts({ brief });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.concepts).toHaveLength(2);
    expect(result.rejected).toHaveLength(1);
  });

  it('fails when every concept is refused rather than showing an empty gallery', async () => {
    mockChatJson.mockResolvedValue(ok({ html: '<h1>Overview</h1>' }));

    const result = await generateConcepts({ brief });

    expect(result).toMatchObject({ ok: false, error_class: 'ContractViolation' });
    if (result.ok) return;
    expect(result.error).toContain('every concept was refused');
    expect(result.rejected).toHaveLength(3);
  });

  it('honours an explicit subset of variants', async () => {
    const result = await generateConcepts({ brief, keys: ['executive'] });
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.concepts.map((c) => c.key)).toEqual(['executive']);
  });
});

describe('the prompt', () => {
  it('hands the model the customer’s vocabulary', () => {
    const prompt = buildConceptPrompt(brief, 'command_center');
    expect(prompt).toContain('Ralph');
    expect(prompt).toContain('Power BI');
  });

  it('states each mechanical rule it will be judged on', () => {
    const prompt = buildConceptPrompt(brief, 'operational');
    expect(prompt).toContain('renamed template');
    expect(prompt).toContain(CONCEPT_LABEL);
    expect(prompt).toContain('NO email addresses');
  });

  it('forbids script, because the concept is rendered sandboxed', () => {
    expect(buildConceptPrompt(brief, 'executive')).toContain('No <script>');
  });

  it('tells it what was never discussed', () => {
    expect(buildConceptPrompt(brief, 'executive')).toContain('NEVER DISCUSSED');
  });

  it('is deterministic', () => {
    expect(buildConceptPrompt(brief, 'executive')).toBe(buildConceptPrompt(brief, 'executive'));
  });
});

/**
 * §20 calls this moment the FINAL FREE WOW — the last thing a prospect sees before deciding
 * to pay. The first real generation passed every correctness check and came back as
 * default-styled tables with stock green buttons, because the prompt demanded product
 * specificity and said nothing about craft. It got exactly what was asked for.
 *
 * "Beautiful" is not decidable. "Nobody styled this" is.
 */
describe('a concept must look designed, not merely rendered', () => {
  // Reuses the module fixture, which already clears the bar. A second, smaller "styled"
  // example would only test whether I can write CSS that satisfies my own threshold.
  const styled = goodHtml;

  it('accepts a concept with a real stylesheet', () => {
    expect(craftViolation(styled)).toBeNull();
  });

  it('refuses html with no style block at all', () => {
    expect(craftViolation('<h1>Ralph</h1><p>Concept</p>')).toContain('browser defaults');
  });

  it('refuses a token gesture at styling', () => {
    expect(craftViolation('<style>body{color:red}</style><p>Concept</p>')).toContain('not a design');
  });

  it('refuses a concept that never sets font-family — the default serif tell', () => {
    const noFont = styled.replace(/font-family:[^;]+;/, '');
    expect(craftViolation(noFont)).toContain('default serif');
  });

  it('refuses a concept with no background or no spacing', () => {
    // Long enough to clear the CSS floor, so it fails for the reason under test rather
    // than for length — otherwise this would pass while proving nothing.
    const flat =
      '<style>body{font-family:ui-sans-serif,system-ui,sans-serif;color:#111}' +
      'h1{font-size:20px;font-weight:600;letter-spacing:-0.01em}' +
      'h2{font-size:16px;font-weight:600}p{line-height:1.5}' +
      '.a{border:1px solid #ccc}.b{border-collapse:collapse}.c{text-align:left}' +
      '.d{font-size:12px;text-transform:uppercase}.e{font-weight:500}.f{line-height:1.4}' +
      '.g{font-variant-numeric:tabular-nums}.h{text-decoration:none}' +
      '.i{border-top:1px solid #eee}.j{border-radius:8px}</style><p>Concept</p>';
    expect(craftViolation(flat)).toContain('default margins');
  });

  it('rejects an unstyled concept through the generator, not just in isolation', async () => {
    mockChatJson.mockResolvedValue(ok({ html: '<h1>Ralph · Power BI</h1><p>Concept</p>' }));

    const { concept, rejected } = await generateConcept({ brief, conceptKey: 'operational' });

    expect(concept).toBeUndefined();
    expect(rejected?.reason).toContain('browser defaults');
  });

  it('holds the CSS floor where the constant says it is', () => {
    expect(MIN_CSS_CHARS).toBe(400);
  });
});

describe('the prompt asks for craft, because the first version did not', () => {
  const prompt = buildConceptPrompt(brief, 'command_center');

  it('says why craft matters here specifically', () => {
    expect(prompt).toContain('LAST THING THEY SEE BEFORE DECIDING WHETHER TO PAY');
  });

  it('names the specific tells of an unstyled page', () => {
    expect(prompt).toContain('font-family');
    expect(prompt).toContain('type scale');
    expect(prompt).toContain('spacing on a rhythm');
  });

  it('forbids the stock button palette that the first generation reached for', () => {
    expect(prompt).toContain('stock green and blue buttons');
  });

  it('requires status to be more than a coloured word, and never colour alone', () => {
    expect(prompt).toContain('Never colour alone');
  });

  it('asks for a considered empty or attention state', () => {
    expect(prompt).toContain('empty or attention state');
  });

  it('steers away from stale specific dates', () => {
    expect(prompt).toContain('obviously illustrative');
  });
});
