-- Materialized views are auto-generated by view_generator.py
-- This file serves as a placeholder and will be populated during discovery

-- Example (generated at runtime):
-- CREATE MATERIALIZED VIEW IF NOT EXISTS entity_performance_features AS
-- SELECT h."id" AS entity_id, h."name" AS entity_name, h."revenue"
-- FROM "leads" h;
--
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_entity_performance_features_entity_id
--   ON entity_performance_features (entity_id);
