import React, { useCallback, useEffect, useState } from 'react';
import { createPhoneHandoff, HandoffCreate } from '../../../services/onboardingApi';

// "Open on your phone" — desktop affordance that mints a single-use QR handoff.
// Scanning it opens Today on the phone already signed in (see PortalHandoffPage).
// The code auto-refreshes shortly before it expires so an open panel always has
// a live code.
const REFRESH_BUFFER_S = 8;

function fmt(sec: number): string {
  const s = Math.max(0, sec);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
}

const OpenOnPhone: React.FC = () => {
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<HandoffCreate | null>(null);
  const [error, setError] = useState('');
  const [remaining, setRemaining] = useState(0);

  const load = useCallback(async () => {
    setError('');
    try {
      const d = await createPhoneHandoff();
      setData(d);
      setRemaining(Math.round((new Date(d.expiresAt).getTime() - Date.now()) / 1000));
    } catch {
      setData(null);
      setError('Could not create a code right now. Try again.');
    }
  }, []);

  // Mint a fresh code whenever the panel opens; clear state on close.
  useEffect(() => {
    if (open) { load(); } else { setData(null); setError(''); }
  }, [open, load]);

  // 1s display countdown, derived from the code's real expiry.
  useEffect(() => {
    if (!open || !data) return;
    const id = window.setInterval(() => {
      setRemaining(Math.round((new Date(data.expiresAt).getTime() - Date.now()) / 1000));
    }, 1000);
    return () => window.clearInterval(id);
  }, [open, data]);

  // Auto-refresh a few seconds before the code expires.
  useEffect(() => {
    if (!open || !data) return;
    const ms = new Date(data.expiresAt).getTime() - Date.now() - REFRESH_BUFFER_S * 1000;
    const id = window.setTimeout(() => { load(); }, Math.max(1000, ms));
    return () => window.clearTimeout(id);
  }, [open, data, load]);

  return (
    <>
      <button type="button" className="phonebtn" onClick={() => setOpen(true)}>
        <svg viewBox="0 0 24 24" fill="none"><rect x="7" y="2" width="10" height="20" rx="2.5" stroke="currentColor" strokeWidth="2" /><path d="M11 18h2" stroke="currentColor" strokeWidth="2" strokeLinecap="round" /></svg>
        Open on your phone
      </button>

      {open && (
        <div className="te-qr-backdrop" role="dialog" aria-modal="true" aria-label="Open Today on your phone" onClick={() => setOpen(false)}>
          <div className="te-qr" onClick={(e) => e.stopPropagation()}>
            <div className="hd">
              <span className="ic" aria-hidden="true">📱</span>
              <div><div className="t">Open Today on your phone</div><div className="s">Point your camera here</div></div>
              <button className="x" type="button" onClick={() => setOpen(false)} aria-label="Close">✕</button>
            </div>

            {error ? (
              <div className="err">
                {error}
                <div style={{ marginTop: 12 }}><button className="te-btn ghost sm" type="button" onClick={load}>Try again</button></div>
              </div>
            ) : data ? (
              <>
                {/* QR SVG is generated by our own backend (qrcode lib), not user
                    input — safe to inline. */}
                <div className="tile" dangerouslySetInnerHTML={{ __html: data.qrSvg }} />
                <div className="cap">Signs you in automatically · refreshes in <b>{fmt(remaining)}</b></div>
              </>
            ) : (
              <div className="tile"><span className="te-muted">Generating…</span></div>
            )}
          </div>
        </div>
      )}
    </>
  );
};

export default OpenOnPhone;
