/**
 * studentDataContract — `docs/DATA_CONTRACT.md`, the field-by-field spec of the
 * two data files, rendered INTO the student's repo.
 *
 * ## Why this file exists
 *
 * `docs/COMMAND_CENTER_DATA_CONTRACT.md` in the platform repo has carried an
 * accurate, worked spec of both files for months. A student has never been able
 * to read it. It is referenced from four source comments and one test, and it
 * reaches no repo, no bundle and no portal surface.
 *
 * This is NOT a case of the answer being absent. STORY-000 states it correctly
 * and repeatedly — `commandCenterStory.ts` names the requirement fields at :626
 * ("`id`, `statement`, `kind`, `priority`, `cluster` and `fulfilled_by`"), gives
 * the join at :413, the guardrail derivation at :513, and the state enum at
 * :556 ("Status per story comes from the progress file,
 * `stories[].verification.state`"). It is right there, four times over.
 *
 * The failure is RETRIEVAL, not coverage. Those four statements sit inside a
 * 26,000-character build brief that a student reads once, at the start, and
 * cannot practically re-scan later. There is no standalone reference to check a
 * half-remembered field name against, and the only two JSON samples ever shipped
 * are of `progress.json` — both deliberately minimal, and both omitting
 * `verification`, the one field that carries completion state. A student has
 * never seen a sample of `plan.json` at all.
 *
 * The measured consequence: a student wrote a Command Center against a
 * `plan.json` he had invented, with `built` on each requirement and `status` on
 * each story. Neither field has existed in any version of our schema — the
 * pickaxe over `planContract.ts` returns zero commits for either, and
 * `PlanStory`'s field list is byte-identical across all five revisions since
 * 2026-08-09. He guessed a shape, and had nowhere to look it up. Reported
 * 2026-08-23; it was the third shape mismatch from the same root cause.
 *
 * `built` and `status` are also the names we use ourselves on `student_tasks`
 * rows, which is a good reason a student would reach for them.
 *
 * ## The rule this document exists to make unmissable
 *
 * `plan.json` is the PLAN and carries no completion state. `progress.json` is
 * the STATE. A page that reads completion out of `plan.json` is reading a file
 * that structurally cannot answer the question — see the "nothing volatile"
 * invariant in `planDocument.ts`, which is why a moving `built` flag could
 * never have lived there.
 *
 * PURE. No I/O, no clock, no plan-dependent content — the bytes are identical
 * for every student, so this file never churns a sync.
 */

/** Where it lands in the student's repo. Under `docs/`, so inside the write allowlist. */
export const STUDENT_DATA_CONTRACT_PATH = 'docs/DATA_CONTRACT.md';

/**
 * The student-facing spec.
 *
 * Deliberately a constant rather than a function of the plan: a per-student
 * rendering would put student data in a reference document and would change
 * whenever their plan did, defeating the content-hash comparison in
 * `changedFiles`. Field names only, never their values.
 */
export function renderStudentDataContract(): string {
  return [
    '# Data Contract — what is in `.colaberry/`',
    '',
    'Your Command Center reads three files. This document is the field-by-field',
    'spec of them. It is generated by the platform and refreshed on every sync,',
    'so it always matches the files you actually have.',
    '',
    '## The one rule that catches everyone',
    '',
    '**`plan.json` is the plan. `progress.json` is the state.**',
    '',
    // Kept one sentence per line, unwrapped, so a student grepping their own repo
    // for the field name they guessed at gets a hit on the sentence that corrects
    // them. A reflowed paragraph would split the phrase and match nothing.
    'There is no `built` field on a requirement.',
    'There is no `status` field on a story.',
    'There never has been, in any version.',
    '',
    'Completion lives in `progress.json` and nowhere else, and the two files are',
    'joined on story id.',
    '',
    'This is not an oversight, it is the design. `plan.json` is committed to your',
    'repo and compared by content hash to decide whether a sync needs to commit at',
    'all. A field that moved as you built would make every sync a commit that',
    'changes nothing. So the plan holds what was planned, and progress holds what',
    'has happened.',
    '',
    '## `.colaberry/plan.json`',
    '',
    'Platform-owned, replaced wholesale when the plan is republished.',
    '`schema_version` is currently `2`. Fields are only ever added, never renamed',
    'or moved, so read the ones you know and ignore the rest.',
    '',
    '```',
    'schema_version   number',
    'project_name     string',
    'descriptor       string',
    '',
    'requirements[]   id            string        REQ-001, …',
    '                 statement     string        the requirement, one sentence',
    '                 kind          string        FUNC | SAFE | REL | NFR | OBS | CONSTRAINT',
    '                 priority      string        must | should',
    '                 cluster       string        the capability it belongs to',
    '                 fulfilled_by  string[]      story ids that fulfil it',
    '',
    'releases[]       key           string        r0, r1, …',
    '                 name          string',
    '                 goal          string',
    '                 demo          string',
    '                 week_start    number',
    '                 week_end      number',
    '                 story_ids     string[]',
    '                 starts_on     YYYY-MM-DD | null',
    '                 ends_on       YYYY-MM-DD | null',
    '                 is_demo_target boolean      true for the release you demo',
    '',
    'stories[]        id            string        STORY-001, …',
    '                 release       string        a release KEY, not a name',
    '                 title         string',
    '                 narrative     string',
    '                 fulfills      string[]      requirement ids',
    '                 owner_agent   string',
    '                 acceptance    string[]      the exact text you are graded on',
    '                 task_guidance string',
    '                 failure_paths string[]',
    '                 blocked_by    string[]      optional',
    '                 due_on        YYYY-MM-DD | null    moves if rescheduled',
    '                 due_baseline_on YYYY-MM-DD | null   the first date given, never moves',
    '',
    'agents[]         id, name, purpose, trigger_type, trigger, inputs[], outputs[],',
    '                 autonomy_level, approval_gates[], escalation_rules[], skills[], owns[]',
    '',
    'project          name, descriptor, repo_url, plan_version, plan_sha256',
    '',
    'schedule         build_start, build_end, demo_day, build_weeks,',
    '                 demo_release_key, roadmap_release_keys[], prep[]',
    '',
    'derived          measures[]    { id, statement }   the numbers you committed to',
    '                 guardrails[]  { id, statement }   your SAFE requirements',
    '                 systems[]     string[]            systems named by CONSTRAINTs',
    '                 roles[]       string[]            roles your stories are written for',
    '                 counts        { … }               totals, precomputed',
    '```',
    '',
    '`derived` is there so every student\'s page agrees on "which of my requirements',
    'are measures" instead of each one guessing with its own regex.',
    '',
    '## `.colaberry/progress.json`',
    '',
    'Co-owned. The platform owns the story list, the criterion text and the whole',
    '`verification` block. Your Claude Code session owns `passed`, `evidence`,',
    '`files_touched`, `tests_added` and `notes`. A sync merges rather than',
    'replaces, so your ticks survive a republish.',
    '',
    '```',
    'schema_version   number',
    'project          string | null',
    'totals           stories_total, stories_verified, stories_submitted,',
    '                 stories_in_progress, stories_not_started,',
    '                 criteria_total, criteria_passed, points_awarded',
    '',
    'stories[]        id                string',
    '                 release           string | null',
    '                 acceptance_total  number | null',
    '                 criteria[]        { text, passed, evidence? }',
    '                 files_touched     string[]',
    '                 tests_added       string[]',
    '                 notes             string | null',
    '                 updated_at        string | null',
    '                 verification      { … } | null    ← completion lives HERE',
    '',
    'verification     state             not_started | in_progress | submitted | verified',
    '                 criteria_passed   number',
    '                 criteria_total    number',
    '                 verified_at       string | null',
    '                 commit_sha        string | null',
    '                 commit_url        string | null',
    '                 commit_at         string | null',
    '                 points_awarded    number | null',
    '                 outstanding       string[]        criterion text still to do',
    '```',
    '',
    '`verification` is **absent until a verification run has happened**. Treat',
    'absent and zero as different things: absent means not measured, zero means',
    'measured as zero. Show "not checked yet", never a `0` that reads as a result.',
    '',
    '## Joining them',
    '',
    'The files are normalised, not duplicated — neither repeats the other:',
    '',
    '```js',
    'const [plan, progress, manifest] = await Promise.all([',
    "  fetch('../.colaberry/plan.json').then((r) => r.json()),",
    "  fetch('../.colaberry/progress.json').then((r) => r.json()),",
    "  fetch('../.colaberry/manifest.json').then((r) => r.json()),",
    ']);',
    '',
    'const progressById = new Map(progress.stories.map((s) => [s.id, s]));',
    '',
    '// Story state — from progress, never from plan.',
    'const rows = plan.stories.map((story) => {',
    '  const p = progressById.get(story.id);',
    '  return {',
    '    ...story,                                    // title, release, acceptance, due_on',
    "    state: p?.verification?.state ?? 'not_started',",
    '    passed: p?.verification?.criteria_passed ?? 0,',
    '    total: p?.verification?.criteria_total ?? story.acceptance.length,',
    '  };',
    '});',
    '',
    '// A requirement is "built" when every story that fulfils it is verified.',
    '// Derived, never stored — this is why there is no `built` field.',
    'const isBuilt = (req) =>',
    '  req.fulfilled_by.length > 0 &&',
    "  req.fulfilled_by.every((id) => progressById.get(id)?.verification?.state === 'verified');",
    '```',
    '',
    '## `.colaberry/manifest.json`',
    '',
    'Freshness, and only freshness. Read `generated_at` for "data as of". It is',
    'the one file allowed to carry a moving timestamp, which is exactly why the',
    'other two are not.',
    '',
    '## What your page cannot show',
    '',
    'These are facts the files do not contain. A page that displays them is',
    'displaying an invention:',
    '',
    '- **The value of any KPI.** We hold the target you committed to, never the',
    '  measurement. That comes from the system you build, once it runs.',
    '- **Whether an integration is connected.** `derived.systems` is a list of',
    '  names taken from requirement text. Nothing in your repo can reach them.',
    '- **Agent run history or success rates.** No agent has run yet.',
    '- **Anything live.** The data is as of the last sync, full stop.',
    '- **Anything about other students.** Not in the files, by design.',
    '',
    'Grey and "not checked from here" is the honest rendering. A confident zero is not.',
    '',
  ].join('\n');
}
